# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import analyze_video as gen_analyze_video
# Registration: app.add_typer(gen_analyze_video.app, name='analyze_video')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help="Video analysis operations. Actions: 'analyze' (default): analyze video for safety/moderation/categories. Use include=['brands','demographics','creative_patterns','deepfake']. 'get_report': get detailed reports (report_type: brand_exposure, evidence_timeline, policy).", no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('analyze')
@handle_errors
def analyze(
    platform: str = typer.Option(None, '--platform', help='Video platform'),
    video_id: str = typer.Option(None, '--video-id', help='Platform-specific video ID'),
    include: str = typer.Option(None, '--include', help='Additional analyses to run (for analyze action)'),
    analysis_id: str = typer.Option(None, '--analysis-id', help='UUID of a video analysis (for get_report)'),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='List of analysis UUIDs for multi-video aggregation (brand_exposure report, Pro)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID to merge text mentions (brand_exposure report)'),
    policy_id: str = typer.Option(None, '--policy-id', help='Policy UUID (for policy report)'),
    report_type: str = typer.Option(None, '--report-type', help='Report type (for get_report action)'),
):
    "Video analysis operations. Actions: 'analyze' (default): analyze video for safety/moderation/categories. Use include=['brands','demographics','creative_patterns','deepfake']. 'get_report': get detailed reports (report_type: brand_exposure, evidence_timeline, policy)."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: analyze_video
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'analyze_video'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'analyze', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('get-report')
@handle_errors
def get_report(
    platform: str = typer.Option(None, '--platform', help='Video platform'),
    video_id: str = typer.Option(None, '--video-id', help='Platform-specific video ID'),
    include: str = typer.Option(None, '--include', help='Additional analyses to run (for analyze action)'),
    analysis_id: str = typer.Option(None, '--analysis-id', help='UUID of a video analysis (for get_report)'),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='List of analysis UUIDs for multi-video aggregation (brand_exposure report, Pro)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID to merge text mentions (brand_exposure report)'),
    policy_id: str = typer.Option(None, '--policy-id', help='Policy UUID (for policy report)'),
    report_type: str = typer.Option(None, '--report-type', help='Report type (for get_report action)'),
):
    "Video analysis operations. Actions: 'analyze' (default): analyze video for safety/moderation/categories. Use include=['brands','demographics','creative_patterns','deepfake']. 'get_report': get detailed reports (report_type: brand_exposure, evidence_timeline, policy)."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: analyze_video
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'analyze_video'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'get_report', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
