# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import analyze_content as gen_analyze_content
# Registration: app.add_typer(gen_analyze_content.app, name='analyze_content')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help='Analyze a specific piece of content in detail. Use when: investigating a viral post, reading a discussion thread, checking who engaged with a post, or getting rich per-post metadata.', no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('analyze-content')
@handle_errors
def analyze_content(
    platform: str = typer.Option(..., '--platform', help='Content platform'),
    content_id: str = typer.Option(..., '--content-id', help='Post/video/thread ID'),
    include: str = typer.Option(None, '--include', help="Analyses to include. Default: ['summary']. 'virality': retweets + quotes (Twitter only). 'engaged_users': who interacted (Twitter/Instagram). 'full_thread': post + comments tree (Reddit only). 'comments': top comments by engagement (all platforms)."),
):
    'Analyze a specific piece of content in detail. Use when: investigating a viral post, reading a discussion thread, checking who engaged with a post, or getting rich per-post metadata.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: analyze_content
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'analyze_content'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'analyze_content', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
