# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import competitor_ads as gen_competitor_ads
# Registration: app.add_typer(gen_competitor_ads.app, name='competitor_ads')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help="Competitive intelligence operations. Actions: 'search' (default): search competitor ads across Meta, TikTok, LinkedIn, Google (5 credits). 'generate_brief': generate competitive intelligence brief for a client (10 credits).", no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('search')
@handle_errors
def search(
    domain: str = typer.Option(None, '--domain', help="Competitor domain for ad search (e.g. 'nike.com')"),
    platform: str = typer.Option(None, '--platform', help='Ad platform to search (default: all)'),
    limit: int = typer.Option(None, '--limit', help='Max ads to return (default 25, max 100)'),
    client_id: str = typer.Option(None, '--client-id', help='Client UUID (for generate_brief)'),
    date_range: str = typer.Option(None, '--date-range', help='Analysis period (for generate_brief)'),
    focus: str = typer.Option(None, '--focus', help='Brief focus area (for generate_brief)'),
    export_pdf: bool = typer.Option(None, '--export-pdf', help='Generate downloadable PDF (for generate_brief)'),
):
    "Competitive intelligence operations. Actions: 'search' (default): search competitor ads across Meta, TikTok, LinkedIn, Google (5 credits). 'generate_brief': generate competitive intelligence brief for a client (10 credits)."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: competitor_ads
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'competitor_ads'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'search', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('generate-brief')
@handle_errors
def generate_brief(
    domain: str = typer.Option(None, '--domain', help="Competitor domain for ad search (e.g. 'nike.com')"),
    platform: str = typer.Option(None, '--platform', help='Ad platform to search (default: all)'),
    limit: int = typer.Option(None, '--limit', help='Max ads to return (default 25, max 100)'),
    client_id: str = typer.Option(None, '--client-id', help='Client UUID (for generate_brief)'),
    date_range: str = typer.Option(None, '--date-range', help='Analysis period (for generate_brief)'),
    focus: str = typer.Option(None, '--focus', help='Brief focus area (for generate_brief)'),
    export_pdf: bool = typer.Option(None, '--export-pdf', help='Generate downloadable PDF (for generate_brief)'),
):
    "Competitive intelligence operations. Actions: 'search' (default): search competitor ads across Meta, TikTok, LinkedIn, Google (5 credits). 'generate_brief': generate competitive intelligence brief for a client (10 credits)."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: competitor_ads
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'competitor_ads'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'generate_brief', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
