# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import creator_profile as gen_creator_profile
# Registration: app.add_typer(gen_creator_profile.app, name='creator_profile')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help="Creator profile operations. Actions: 'get' (default): detailed analytics with include[] sections. 'enrich': full IC enrichment (1.0 credit). 'enrich_raw': basic platform data (0.03 credit). 'connected_socials': cross-platform linked accounts (0.5 credit). 'check_credits': remaining IC credits. 'list_content': recent posts (0.03 credit). 'get_post': post details with transcript/comments (0.03 credit). 'capture_stories': capture ephemeral Instagram Stories (Pro only).", no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('get')
@handle_errors
def get(
    platform: str = typer.Option(None, '--platform', help="Creator's platform"),
    username: str = typer.Option(None, '--username', help="Creator's username (without @ prefix)"),
    include: str = typer.Option(None, '--include', help="Data sections for action=get. Default: ['analytics']."),
    include_audience: bool = typer.Option(None, '--include-audience', help='Include audience analytics (for enrich, default true)'),
    post_url: str = typer.Option(None, '--post-url', help='Specific post URL (for get_post)'),
    content_type: str = typer.Option(None, '--content-type', help='Post data type (for get_post, default: data)'),
    page: int = typer.Option(None, '--page', help='Pagination (for list_content, default 0)'),
):
    "Creator profile operations. Actions: 'get' (default): detailed analytics with include[] sections. 'enrich': full IC enrichment (1.0 credit). 'enrich_raw': basic platform data (0.03 credit). 'connected_socials': cross-platform linked accounts (0.5 credit). 'check_credits': remaining IC credits. 'list_content': recent posts (0.03 credit). 'get_post': post details with transcript/comments (0.03 credit). 'capture_stories': capture ephemeral Instagram Stories (Pro only)."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: creator_profile
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'creator_profile'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'get', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('enrich')
@handle_errors
def enrich(
    platform: str = typer.Option(None, '--platform', help="Creator's platform"),
    username: str = typer.Option(None, '--username', help="Creator's username (without @ prefix)"),
    include: str = typer.Option(None, '--include', help="Data sections for action=get. Default: ['analytics']."),
    include_audience: bool = typer.Option(None, '--include-audience', help='Include audience analytics (for enrich, default true)'),
    post_url: str = typer.Option(None, '--post-url', help='Specific post URL (for get_post)'),
    content_type: str = typer.Option(None, '--content-type', help='Post data type (for get_post, default: data)'),
    page: int = typer.Option(None, '--page', help='Pagination (for list_content, default 0)'),
):
    "Creator profile operations. Actions: 'get' (default): detailed analytics with include[] sections. 'enrich': full IC enrichment (1.0 credit). 'enrich_raw': basic platform data (0.03 credit). 'connected_socials': cross-platform linked accounts (0.5 credit). 'check_credits': remaining IC credits. 'list_content': recent posts (0.03 credit). 'get_post': post details with transcript/comments (0.03 credit). 'capture_stories': capture ephemeral Instagram Stories (Pro only)."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: creator_profile
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'creator_profile'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'enrich', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('enrich-raw')
@handle_errors
def enrich_raw(
    platform: str = typer.Option(None, '--platform', help="Creator's platform"),
    username: str = typer.Option(None, '--username', help="Creator's username (without @ prefix)"),
    include: str = typer.Option(None, '--include', help="Data sections for action=get. Default: ['analytics']."),
    include_audience: bool = typer.Option(None, '--include-audience', help='Include audience analytics (for enrich, default true)'),
    post_url: str = typer.Option(None, '--post-url', help='Specific post URL (for get_post)'),
    content_type: str = typer.Option(None, '--content-type', help='Post data type (for get_post, default: data)'),
    page: int = typer.Option(None, '--page', help='Pagination (for list_content, default 0)'),
):
    "Creator profile operations. Actions: 'get' (default): detailed analytics with include[] sections. 'enrich': full IC enrichment (1.0 credit). 'enrich_raw': basic platform data (0.03 credit). 'connected_socials': cross-platform linked accounts (0.5 credit). 'check_credits': remaining IC credits. 'list_content': recent posts (0.03 credit). 'get_post': post details with transcript/comments (0.03 credit). 'capture_stories': capture ephemeral Instagram Stories (Pro only)."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: creator_profile
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'creator_profile'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'enrich_raw', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('connected-socials')
@handle_errors
def connected_socials(
    platform: str = typer.Option(None, '--platform', help="Creator's platform"),
    username: str = typer.Option(None, '--username', help="Creator's username (without @ prefix)"),
    include: str = typer.Option(None, '--include', help="Data sections for action=get. Default: ['analytics']."),
    include_audience: bool = typer.Option(None, '--include-audience', help='Include audience analytics (for enrich, default true)'),
    post_url: str = typer.Option(None, '--post-url', help='Specific post URL (for get_post)'),
    content_type: str = typer.Option(None, '--content-type', help='Post data type (for get_post, default: data)'),
    page: int = typer.Option(None, '--page', help='Pagination (for list_content, default 0)'),
):
    "Creator profile operations. Actions: 'get' (default): detailed analytics with include[] sections. 'enrich': full IC enrichment (1.0 credit). 'enrich_raw': basic platform data (0.03 credit). 'connected_socials': cross-platform linked accounts (0.5 credit). 'check_credits': remaining IC credits. 'list_content': recent posts (0.03 credit). 'get_post': post details with transcript/comments (0.03 credit). 'capture_stories': capture ephemeral Instagram Stories (Pro only)."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: creator_profile
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'creator_profile'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'connected_socials', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('check-credits')
@handle_errors
def check_credits(
    platform: str = typer.Option(None, '--platform', help="Creator's platform"),
    username: str = typer.Option(None, '--username', help="Creator's username (without @ prefix)"),
    include: str = typer.Option(None, '--include', help="Data sections for action=get. Default: ['analytics']."),
    include_audience: bool = typer.Option(None, '--include-audience', help='Include audience analytics (for enrich, default true)'),
    post_url: str = typer.Option(None, '--post-url', help='Specific post URL (for get_post)'),
    content_type: str = typer.Option(None, '--content-type', help='Post data type (for get_post, default: data)'),
    page: int = typer.Option(None, '--page', help='Pagination (for list_content, default 0)'),
):
    "Creator profile operations. Actions: 'get' (default): detailed analytics with include[] sections. 'enrich': full IC enrichment (1.0 credit). 'enrich_raw': basic platform data (0.03 credit). 'connected_socials': cross-platform linked accounts (0.5 credit). 'check_credits': remaining IC credits. 'list_content': recent posts (0.03 credit). 'get_post': post details with transcript/comments (0.03 credit). 'capture_stories': capture ephemeral Instagram Stories (Pro only)."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: creator_profile
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'creator_profile'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'check_credits', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('list-content')
@handle_errors
def list_content(
    platform: str = typer.Option(None, '--platform', help="Creator's platform"),
    username: str = typer.Option(None, '--username', help="Creator's username (without @ prefix)"),
    include: str = typer.Option(None, '--include', help="Data sections for action=get. Default: ['analytics']."),
    include_audience: bool = typer.Option(None, '--include-audience', help='Include audience analytics (for enrich, default true)'),
    post_url: str = typer.Option(None, '--post-url', help='Specific post URL (for get_post)'),
    content_type: str = typer.Option(None, '--content-type', help='Post data type (for get_post, default: data)'),
    page: int = typer.Option(None, '--page', help='Pagination (for list_content, default 0)'),
):
    "Creator profile operations. Actions: 'get' (default): detailed analytics with include[] sections. 'enrich': full IC enrichment (1.0 credit). 'enrich_raw': basic platform data (0.03 credit). 'connected_socials': cross-platform linked accounts (0.5 credit). 'check_credits': remaining IC credits. 'list_content': recent posts (0.03 credit). 'get_post': post details with transcript/comments (0.03 credit). 'capture_stories': capture ephemeral Instagram Stories (Pro only)."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: creator_profile
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'creator_profile'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'list_content', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('get-post')
@handle_errors
def get_post(
    platform: str = typer.Option(None, '--platform', help="Creator's platform"),
    username: str = typer.Option(None, '--username', help="Creator's username (without @ prefix)"),
    include: str = typer.Option(None, '--include', help="Data sections for action=get. Default: ['analytics']."),
    include_audience: bool = typer.Option(None, '--include-audience', help='Include audience analytics (for enrich, default true)'),
    post_url: str = typer.Option(None, '--post-url', help='Specific post URL (for get_post)'),
    content_type: str = typer.Option(None, '--content-type', help='Post data type (for get_post, default: data)'),
    page: int = typer.Option(None, '--page', help='Pagination (for list_content, default 0)'),
):
    "Creator profile operations. Actions: 'get' (default): detailed analytics with include[] sections. 'enrich': full IC enrichment (1.0 credit). 'enrich_raw': basic platform data (0.03 credit). 'connected_socials': cross-platform linked accounts (0.5 credit). 'check_credits': remaining IC credits. 'list_content': recent posts (0.03 credit). 'get_post': post details with transcript/comments (0.03 credit). 'capture_stories': capture ephemeral Instagram Stories (Pro only)."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: creator_profile
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'creator_profile'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'get_post', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('capture-stories')
@handle_errors
def capture_stories(
    platform: str = typer.Option(None, '--platform', help="Creator's platform"),
    username: str = typer.Option(None, '--username', help="Creator's username (without @ prefix)"),
    include: str = typer.Option(None, '--include', help="Data sections for action=get. Default: ['analytics']."),
    include_audience: bool = typer.Option(None, '--include-audience', help='Include audience analytics (for enrich, default true)'),
    post_url: str = typer.Option(None, '--post-url', help='Specific post URL (for get_post)'),
    content_type: str = typer.Option(None, '--content-type', help='Post data type (for get_post, default: data)'),
    page: int = typer.Option(None, '--page', help='Pagination (for list_content, default 0)'),
):
    "Creator profile operations. Actions: 'get' (default): detailed analytics with include[] sections. 'enrich': full IC enrichment (1.0 credit). 'enrich_raw': basic platform data (0.03 credit). 'connected_socials': cross-platform linked accounts (0.5 credit). 'check_credits': remaining IC credits. 'list_content': recent posts (0.03 credit). 'get_post': post details with transcript/comments (0.03 credit). 'capture_stories': capture ephemeral Instagram Stories (Pro only)."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: creator_profile
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'creator_profile'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'capture_stories', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
