# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import detect_fraud as gen_detect_fraud
# Registration: app.add_typer(gen_detect_fraud.app, name='detect_fraud')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help='Analyze a creator for fraud indicators: fake followers, bot comments, engagement anomalies. Only use when the user explicitly asks for fraud analysis, authenticity checks, or audience quality. Returns an Audience Quality Score (AQS 0-100) and risk assessment. Grades: excellent (90-100), very_good (80-89), good (60-79), poor (40-59), critical (<40). Only supports TikTok and Instagram.', no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('detect-fraud')
@handle_errors
def detect_fraud(
    platform: str = typer.Option(..., '--platform', help="Creator's platform (TikTok or Instagram only)"),
    username: str = typer.Option(..., '--username', help="Creator's username (without @)"),
):
    'Analyze a creator for fraud indicators: fake followers, bot comments, engagement anomalies. Only use when the user explicitly asks for fraud analysis, authenticity checks, or audience quality. Returns an Audience Quality Score (AQS 0-100) and risk assessment. Grades: excellent (90-100), very_good (80-89), good (60-79), poor (40-59), critical (<40). Only supports TikTok and Instagram.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: detect_fraud
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'detect_fraud'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'detect_fraud', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
