# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import discover_creators as gen_discover_creators
# Registration: app.add_typer(gen_discover_creators.app, name='discover_creators')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help="Find creators and influencers across social platforms. mode='search' (default): find by keywords/filters. mode='similar': find lookalikes of a reference creator. mode='email': reverse-lookup creator profiles by email. mode='network': get followers/following of a creator (Twitter/Instagram only).", no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('discover-creators')
@handle_errors
def discover_creators(
    mode: str = typer.Option(None, '--mode', help='search=keyword discovery, similar=lookalikes, email=reverse lookup, network=social graph'),
    keywords: str = typer.Option(None, '--keywords', help='Search keywords or topic (mode=search)'),
    platforms: str = typer.Option(None, '--platforms', help='Platforms to search. Default: all available for the mode.'),
    reference_username: str = typer.Option(None, '--reference-username', help='Username for mode=network, or external_id for mode=similar (from creator_profile)'),
    reference_platform: str = typer.Option(None, '--reference-platform', help='Platform of reference creator'),
    email: str = typer.Option(None, '--email', help='Email address for mode=email'),
    connection_type: str = typer.Option(None, '--connection-type', help='For mode=network: which connections to retrieve. Default: followers'),
    hashtags: str = typer.Option(None, '--hashtags', help='Filter by hashtag usage'),
    audience_location: str = typer.Option(None, '--audience-location', help='Filter by audience country (name or UUID)'),
    audience_credibility: str = typer.Option(None, '--audience-credibility', help='Filter by audience credibility score'),
    is_verified: bool = typer.Option(None, '--is-verified', help='Filter to verified creators only'),
    creator_gender: str = typer.Option(None, '--creator-gender', help='Filter by creator gender'),
    audience_gender: str = typer.Option(None, '--audience-gender', help='Filter by audience gender skew'),
    audience_age_min: int = typer.Option(None, '--audience-age-min', help='Minimum audience age filter'),
    audience_age_max: int = typer.Option(None, '--audience-age-max', help='Maximum audience age filter'),
    audience_language: str = typer.Option(None, '--audience-language', help="Filter by audience language (ISO 639-1 code, e.g., 'en')"),
    has_sponsored_posts: bool = typer.Option(None, '--has-sponsored-posts', help='Filter to creators with sponsored post history'),
    topic_relevance: str = typer.Option(None, '--topic-relevance', help="Filter by topic relevance tags (e.g., ['Fashion', 'Beauty'])."),
    brand_affinity: str = typer.Option(None, '--brand-affinity', help="Filter by brand affinity (e.g., ['Nike', 'Adidas'])."),
    content_count_min: int = typer.Option(None, '--content-count-min', help='Minimum number of content items a creator must have.'),
    min_followers: int = typer.Option(None, '--min-followers', help='Minimum follower count'),
    max_followers: int = typer.Option(None, '--max-followers', help='Maximum follower count'),
    min_engagement_rate: float = typer.Option(None, '--min-engagement-rate', help='Minimum engagement rate (decimal 0.0-1.0, e.g., 0.03 for 3%)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort order. Default: ENGAGEMENT_RATE'),
    limit: int = typer.Option(None, '--limit', help='Max results (1-100). Default 20'),
):
    "Find creators and influencers across social platforms. mode='search' (default): find by keywords/filters. mode='similar': find lookalikes of a reference creator. mode='email': reverse-lookup creator profiles by email. mode='network': get followers/following of a creator (Twitter/Instagram only)."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: discover_creators
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'discover_creators'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'discover_creators', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
