# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import evaluate_creators as gen_evaluate_creators
# Registration: app.add_typer(gen_evaluate_creators.app, name='evaluate_creators')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help='Evaluate one or more creators for campaign suitability. Use for creator brand-safety checks and audience overlap between shortlisted creators. Pro tier required.', no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('evaluate-creators')
@handle_errors
def evaluate_creators(
    creators: str = typer.Option(..., '--creators', help='List of creators to evaluate (max 10).'),
    evaluations: str = typer.Option(..., '--evaluations', help='Evaluations to run.'),
):
    'Evaluate one or more creators for campaign suitability. Use for creator brand-safety checks and audience overlap between shortlisted creators. Pro tier required.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: evaluate_creators
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'evaluate_creators'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'evaluate_creators', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
