# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import generate_content as gen_generate_content
# Registration: app.add_typer(gen_generate_content.app, name='generate_content')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help="Generate content from workspace data — creative briefs, social posts, blog articles, newsletters, video scripts, ad copy, or rewrites. Reads a workspace collection and synthesizes insights via the selected action. Specify the client_vertical (e.g. 'organic skincare') and optionally focus_areas. Pro-only.", no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('synthesize')
@handle_errors
def synthesize(
    collection_name: str = typer.Option(None, '--collection-name', help='Workspace collection name (synthesize action)'),
    client_vertical: str = typer.Option(None, '--client-vertical', help="Client's industry vertical (synthesize action)"),
    focus_areas: str = typer.Option(None, '--focus-areas', help='Optional focus areas (synthesize action)'),
    voice_profile_id: str = typer.Option(None, '--voice-profile-id', help='Voice profile UUID for voice-matched content (all actions except synthesize)'),
    topic: str = typer.Option(None, '--topic', help='Topic for content generation (social_posts, blog_article, newsletter, video_script, ad_copy)'),
    keywords: str = typer.Option(None, '--keywords', help='Target keywords (blog_article)'),
    platforms: str = typer.Option(None, '--platforms', help='Target platforms (social_posts, ad_copy)'),
    count: int = typer.Option(None, '--count', help='Number of posts per platform (social_posts)'),
    target_word_count: int = typer.Option(None, '--target-word-count', help='Target word count (blog_article)'),
    content: str = typer.Option(None, '--content', help='Content to rewrite (rewrite action)'),
    tones: str = typer.Option(None, '--tones', help='Tone variants (rewrite)'),
    campaign_objective: str = typer.Option(None, '--campaign-objective', help='Campaign objective (ad_copy)'),
    duration_target: int = typer.Option(None, '--duration-target', help='Target duration in seconds (video_script)'),
    segment: str = typer.Option(None, '--segment', help='Audience segment (newsletter)'),
    target_platform: str = typer.Option(None, '--target-platform', help='Target platform for adaptation (rewrite)'),
):
    "Generate content from workspace data — creative briefs, social posts, blog articles, newsletters, video scripts, ad copy, or rewrites. Reads a workspace collection and synthesizes insights via the selected action. Specify the client_vertical (e.g. 'organic skincare') and optionally focus_areas. Pro-only."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: generate_content
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'generate_content'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'synthesize', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('social-posts')
@handle_errors
def social_posts(
    collection_name: str = typer.Option(None, '--collection-name', help='Workspace collection name (synthesize action)'),
    client_vertical: str = typer.Option(None, '--client-vertical', help="Client's industry vertical (synthesize action)"),
    focus_areas: str = typer.Option(None, '--focus-areas', help='Optional focus areas (synthesize action)'),
    voice_profile_id: str = typer.Option(None, '--voice-profile-id', help='Voice profile UUID for voice-matched content (all actions except synthesize)'),
    topic: str = typer.Option(None, '--topic', help='Topic for content generation (social_posts, blog_article, newsletter, video_script, ad_copy)'),
    keywords: str = typer.Option(None, '--keywords', help='Target keywords (blog_article)'),
    platforms: str = typer.Option(None, '--platforms', help='Target platforms (social_posts, ad_copy)'),
    count: int = typer.Option(None, '--count', help='Number of posts per platform (social_posts)'),
    target_word_count: int = typer.Option(None, '--target-word-count', help='Target word count (blog_article)'),
    content: str = typer.Option(None, '--content', help='Content to rewrite (rewrite action)'),
    tones: str = typer.Option(None, '--tones', help='Tone variants (rewrite)'),
    campaign_objective: str = typer.Option(None, '--campaign-objective', help='Campaign objective (ad_copy)'),
    duration_target: int = typer.Option(None, '--duration-target', help='Target duration in seconds (video_script)'),
    segment: str = typer.Option(None, '--segment', help='Audience segment (newsletter)'),
    target_platform: str = typer.Option(None, '--target-platform', help='Target platform for adaptation (rewrite)'),
):
    "Generate content from workspace data — creative briefs, social posts, blog articles, newsletters, video scripts, ad copy, or rewrites. Reads a workspace collection and synthesizes insights via the selected action. Specify the client_vertical (e.g. 'organic skincare') and optionally focus_areas. Pro-only."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: generate_content
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'generate_content'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'social_posts', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('blog-article')
@handle_errors
def blog_article(
    collection_name: str = typer.Option(None, '--collection-name', help='Workspace collection name (synthesize action)'),
    client_vertical: str = typer.Option(None, '--client-vertical', help="Client's industry vertical (synthesize action)"),
    focus_areas: str = typer.Option(None, '--focus-areas', help='Optional focus areas (synthesize action)'),
    voice_profile_id: str = typer.Option(None, '--voice-profile-id', help='Voice profile UUID for voice-matched content (all actions except synthesize)'),
    topic: str = typer.Option(None, '--topic', help='Topic for content generation (social_posts, blog_article, newsletter, video_script, ad_copy)'),
    keywords: str = typer.Option(None, '--keywords', help='Target keywords (blog_article)'),
    platforms: str = typer.Option(None, '--platforms', help='Target platforms (social_posts, ad_copy)'),
    count: int = typer.Option(None, '--count', help='Number of posts per platform (social_posts)'),
    target_word_count: int = typer.Option(None, '--target-word-count', help='Target word count (blog_article)'),
    content: str = typer.Option(None, '--content', help='Content to rewrite (rewrite action)'),
    tones: str = typer.Option(None, '--tones', help='Tone variants (rewrite)'),
    campaign_objective: str = typer.Option(None, '--campaign-objective', help='Campaign objective (ad_copy)'),
    duration_target: int = typer.Option(None, '--duration-target', help='Target duration in seconds (video_script)'),
    segment: str = typer.Option(None, '--segment', help='Audience segment (newsletter)'),
    target_platform: str = typer.Option(None, '--target-platform', help='Target platform for adaptation (rewrite)'),
):
    "Generate content from workspace data — creative briefs, social posts, blog articles, newsletters, video scripts, ad copy, or rewrites. Reads a workspace collection and synthesizes insights via the selected action. Specify the client_vertical (e.g. 'organic skincare') and optionally focus_areas. Pro-only."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: generate_content
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'generate_content'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'blog_article', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('newsletter')
@handle_errors
def newsletter(
    collection_name: str = typer.Option(None, '--collection-name', help='Workspace collection name (synthesize action)'),
    client_vertical: str = typer.Option(None, '--client-vertical', help="Client's industry vertical (synthesize action)"),
    focus_areas: str = typer.Option(None, '--focus-areas', help='Optional focus areas (synthesize action)'),
    voice_profile_id: str = typer.Option(None, '--voice-profile-id', help='Voice profile UUID for voice-matched content (all actions except synthesize)'),
    topic: str = typer.Option(None, '--topic', help='Topic for content generation (social_posts, blog_article, newsletter, video_script, ad_copy)'),
    keywords: str = typer.Option(None, '--keywords', help='Target keywords (blog_article)'),
    platforms: str = typer.Option(None, '--platforms', help='Target platforms (social_posts, ad_copy)'),
    count: int = typer.Option(None, '--count', help='Number of posts per platform (social_posts)'),
    target_word_count: int = typer.Option(None, '--target-word-count', help='Target word count (blog_article)'),
    content: str = typer.Option(None, '--content', help='Content to rewrite (rewrite action)'),
    tones: str = typer.Option(None, '--tones', help='Tone variants (rewrite)'),
    campaign_objective: str = typer.Option(None, '--campaign-objective', help='Campaign objective (ad_copy)'),
    duration_target: int = typer.Option(None, '--duration-target', help='Target duration in seconds (video_script)'),
    segment: str = typer.Option(None, '--segment', help='Audience segment (newsletter)'),
    target_platform: str = typer.Option(None, '--target-platform', help='Target platform for adaptation (rewrite)'),
):
    "Generate content from workspace data — creative briefs, social posts, blog articles, newsletters, video scripts, ad copy, or rewrites. Reads a workspace collection and synthesizes insights via the selected action. Specify the client_vertical (e.g. 'organic skincare') and optionally focus_areas. Pro-only."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: generate_content
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'generate_content'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'newsletter', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('video-script')
@handle_errors
def video_script(
    collection_name: str = typer.Option(None, '--collection-name', help='Workspace collection name (synthesize action)'),
    client_vertical: str = typer.Option(None, '--client-vertical', help="Client's industry vertical (synthesize action)"),
    focus_areas: str = typer.Option(None, '--focus-areas', help='Optional focus areas (synthesize action)'),
    voice_profile_id: str = typer.Option(None, '--voice-profile-id', help='Voice profile UUID for voice-matched content (all actions except synthesize)'),
    topic: str = typer.Option(None, '--topic', help='Topic for content generation (social_posts, blog_article, newsletter, video_script, ad_copy)'),
    keywords: str = typer.Option(None, '--keywords', help='Target keywords (blog_article)'),
    platforms: str = typer.Option(None, '--platforms', help='Target platforms (social_posts, ad_copy)'),
    count: int = typer.Option(None, '--count', help='Number of posts per platform (social_posts)'),
    target_word_count: int = typer.Option(None, '--target-word-count', help='Target word count (blog_article)'),
    content: str = typer.Option(None, '--content', help='Content to rewrite (rewrite action)'),
    tones: str = typer.Option(None, '--tones', help='Tone variants (rewrite)'),
    campaign_objective: str = typer.Option(None, '--campaign-objective', help='Campaign objective (ad_copy)'),
    duration_target: int = typer.Option(None, '--duration-target', help='Target duration in seconds (video_script)'),
    segment: str = typer.Option(None, '--segment', help='Audience segment (newsletter)'),
    target_platform: str = typer.Option(None, '--target-platform', help='Target platform for adaptation (rewrite)'),
):
    "Generate content from workspace data — creative briefs, social posts, blog articles, newsletters, video scripts, ad copy, or rewrites. Reads a workspace collection and synthesizes insights via the selected action. Specify the client_vertical (e.g. 'organic skincare') and optionally focus_areas. Pro-only."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: generate_content
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'generate_content'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'video_script', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('ad-copy')
@handle_errors
def ad_copy(
    collection_name: str = typer.Option(None, '--collection-name', help='Workspace collection name (synthesize action)'),
    client_vertical: str = typer.Option(None, '--client-vertical', help="Client's industry vertical (synthesize action)"),
    focus_areas: str = typer.Option(None, '--focus-areas', help='Optional focus areas (synthesize action)'),
    voice_profile_id: str = typer.Option(None, '--voice-profile-id', help='Voice profile UUID for voice-matched content (all actions except synthesize)'),
    topic: str = typer.Option(None, '--topic', help='Topic for content generation (social_posts, blog_article, newsletter, video_script, ad_copy)'),
    keywords: str = typer.Option(None, '--keywords', help='Target keywords (blog_article)'),
    platforms: str = typer.Option(None, '--platforms', help='Target platforms (social_posts, ad_copy)'),
    count: int = typer.Option(None, '--count', help='Number of posts per platform (social_posts)'),
    target_word_count: int = typer.Option(None, '--target-word-count', help='Target word count (blog_article)'),
    content: str = typer.Option(None, '--content', help='Content to rewrite (rewrite action)'),
    tones: str = typer.Option(None, '--tones', help='Tone variants (rewrite)'),
    campaign_objective: str = typer.Option(None, '--campaign-objective', help='Campaign objective (ad_copy)'),
    duration_target: int = typer.Option(None, '--duration-target', help='Target duration in seconds (video_script)'),
    segment: str = typer.Option(None, '--segment', help='Audience segment (newsletter)'),
    target_platform: str = typer.Option(None, '--target-platform', help='Target platform for adaptation (rewrite)'),
):
    "Generate content from workspace data — creative briefs, social posts, blog articles, newsletters, video scripts, ad copy, or rewrites. Reads a workspace collection and synthesizes insights via the selected action. Specify the client_vertical (e.g. 'organic skincare') and optionally focus_areas. Pro-only."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: generate_content
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'generate_content'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'ad_copy', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('rewrite')
@handle_errors
def rewrite(
    collection_name: str = typer.Option(None, '--collection-name', help='Workspace collection name (synthesize action)'),
    client_vertical: str = typer.Option(None, '--client-vertical', help="Client's industry vertical (synthesize action)"),
    focus_areas: str = typer.Option(None, '--focus-areas', help='Optional focus areas (synthesize action)'),
    voice_profile_id: str = typer.Option(None, '--voice-profile-id', help='Voice profile UUID for voice-matched content (all actions except synthesize)'),
    topic: str = typer.Option(None, '--topic', help='Topic for content generation (social_posts, blog_article, newsletter, video_script, ad_copy)'),
    keywords: str = typer.Option(None, '--keywords', help='Target keywords (blog_article)'),
    platforms: str = typer.Option(None, '--platforms', help='Target platforms (social_posts, ad_copy)'),
    count: int = typer.Option(None, '--count', help='Number of posts per platform (social_posts)'),
    target_word_count: int = typer.Option(None, '--target-word-count', help='Target word count (blog_article)'),
    content: str = typer.Option(None, '--content', help='Content to rewrite (rewrite action)'),
    tones: str = typer.Option(None, '--tones', help='Tone variants (rewrite)'),
    campaign_objective: str = typer.Option(None, '--campaign-objective', help='Campaign objective (ad_copy)'),
    duration_target: int = typer.Option(None, '--duration-target', help='Target duration in seconds (video_script)'),
    segment: str = typer.Option(None, '--segment', help='Audience segment (newsletter)'),
    target_platform: str = typer.Option(None, '--target-platform', help='Target platform for adaptation (rewrite)'),
):
    "Generate content from workspace data — creative briefs, social posts, blog articles, newsletters, video scripts, ad copy, or rewrites. Reads a workspace collection and synthesizes insights via the selected action. Specify the client_vertical (e.g. 'organic skincare') and optionally focus_areas. Pro-only."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: generate_content
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'generate_content'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'rewrite', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
