# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import geo_check_visibility as gen_geo_check_visibility
# Registration: app.add_typer(gen_geo_check_visibility.app, name='geo_check_visibility')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help='Check brand visibility across AI search platforms (ChatGPT, Perplexity, Gemini, etc.). Queries AI engines with brand + keywords and reports whether the brand is cited, mentioned in text, and which URLs are cited.', no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('geo-check-visibility')
@handle_errors
def geo_check_visibility(
    brand: str = typer.Option(..., '--brand', help='Brand name to check visibility for'),
    keywords: str = typer.Option(..., '--keywords', help="Comma-separated keywords to query with the brand (e.g. 'best CRM,marketing tools')"),
    platforms: str = typer.Option(None, '--platforms', help='AI platforms to check. Default: chatgpt, perplexity, gemini.'),
    country: str = typer.Option(None, '--country', help="ISO 3166-1 alpha-2 country code for geo-targeted queries (e.g. 'US', 'GB')"),
):
    'Check brand visibility across AI search platforms (ChatGPT, Perplexity, Gemini, etc.). Queries AI engines with brand + keywords and reports whether the brand is cited, mentioned in text, and which URLs are cited.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: geo_check_visibility
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'geo_check_visibility'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'geo_check_visibility', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
