# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import manage_monitor as gen_manage_monitor
# Registration: app.add_typer(gen_manage_monitor.app, name='manage_monitor')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help='Manage brand monitors and configuration. Actions: create, update, delete, run_now, create_alert, update_alert, delete_alert, test_alert, list_alerts, list_events, view_changelog, approve, reject.', no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('create')
@handle_errors
def create(
    name: str = typer.Option(None, '--name', help="Monitor name (for create, e.g. 'Nike Brand Monitor')"),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to track (for create/update)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID (for update/delete/run_now/config actions)'),
    sources: str = typer.Option(None, '--sources', help='Data sources (for create/update). Default: twitter, instagram, reddit'),
    boolean_query: str = typer.Option(None, '--boolean-query', help='Advanced Boolean query for FTS (for create/update)'),
    languages: str = typer.Option(None, '--languages', help="ISO 639-1 language codes to filter by (for create/update, e.g. ['en', 'es'])"),
    regions: str = typer.Option(None, '--regions', help="ISO 3166-1 region codes to filter by (for create/update, e.g. ['US', 'GB'])"),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names for share-of-voice analysis (max 10, for create/update)'),
    is_active: bool = typer.Option(None, '--is-active', help='Enable/disable the monitor (for update)'),
    entry_id: str = typer.Option(None, '--entry-id', help='Changelog entry UUID (for approve/reject)'),
    rule_id: str = typer.Option(None, '--rule-id', help='Alert rule UUID (for update_alert/delete_alert/test_alert)'),
    webhook_url: str = typer.Option(None, '--webhook-url', help='Webhook URL (for create_alert)'),
    threshold_pct: int = typer.Option(None, '--threshold-pct', help='Spike threshold percentage (for create_alert, default 200)'),
    window_hours: int = typer.Option(None, '--window-hours', help='Detection window in hours (for create_alert)'),
    cooldown_minutes: int = typer.Option(None, '--cooldown-minutes', help='Min minutes between alerts (for create_alert, default 60)'),
    limit: int = typer.Option(None, '--limit', help='Max entries to return (for list_events/view_changelog)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for list_events)'),
):
    'Manage brand monitors and configuration. Actions: create, update, delete, run_now, create_alert, update_alert, delete_alert, test_alert, list_alerts, list_events, view_changelog, approve, reject.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'create', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('update')
@handle_errors
def update(
    name: str = typer.Option(None, '--name', help="Monitor name (for create, e.g. 'Nike Brand Monitor')"),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to track (for create/update)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID (for update/delete/run_now/config actions)'),
    sources: str = typer.Option(None, '--sources', help='Data sources (for create/update). Default: twitter, instagram, reddit'),
    boolean_query: str = typer.Option(None, '--boolean-query', help='Advanced Boolean query for FTS (for create/update)'),
    languages: str = typer.Option(None, '--languages', help="ISO 639-1 language codes to filter by (for create/update, e.g. ['en', 'es'])"),
    regions: str = typer.Option(None, '--regions', help="ISO 3166-1 region codes to filter by (for create/update, e.g. ['US', 'GB'])"),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names for share-of-voice analysis (max 10, for create/update)'),
    is_active: bool = typer.Option(None, '--is-active', help='Enable/disable the monitor (for update)'),
    entry_id: str = typer.Option(None, '--entry-id', help='Changelog entry UUID (for approve/reject)'),
    rule_id: str = typer.Option(None, '--rule-id', help='Alert rule UUID (for update_alert/delete_alert/test_alert)'),
    webhook_url: str = typer.Option(None, '--webhook-url', help='Webhook URL (for create_alert)'),
    threshold_pct: int = typer.Option(None, '--threshold-pct', help='Spike threshold percentage (for create_alert, default 200)'),
    window_hours: int = typer.Option(None, '--window-hours', help='Detection window in hours (for create_alert)'),
    cooldown_minutes: int = typer.Option(None, '--cooldown-minutes', help='Min minutes between alerts (for create_alert, default 60)'),
    limit: int = typer.Option(None, '--limit', help='Max entries to return (for list_events/view_changelog)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for list_events)'),
):
    'Manage brand monitors and configuration. Actions: create, update, delete, run_now, create_alert, update_alert, delete_alert, test_alert, list_alerts, list_events, view_changelog, approve, reject.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'update', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('delete')
@handle_errors
def delete(
    name: str = typer.Option(None, '--name', help="Monitor name (for create, e.g. 'Nike Brand Monitor')"),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to track (for create/update)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID (for update/delete/run_now/config actions)'),
    sources: str = typer.Option(None, '--sources', help='Data sources (for create/update). Default: twitter, instagram, reddit'),
    boolean_query: str = typer.Option(None, '--boolean-query', help='Advanced Boolean query for FTS (for create/update)'),
    languages: str = typer.Option(None, '--languages', help="ISO 639-1 language codes to filter by (for create/update, e.g. ['en', 'es'])"),
    regions: str = typer.Option(None, '--regions', help="ISO 3166-1 region codes to filter by (for create/update, e.g. ['US', 'GB'])"),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names for share-of-voice analysis (max 10, for create/update)'),
    is_active: bool = typer.Option(None, '--is-active', help='Enable/disable the monitor (for update)'),
    entry_id: str = typer.Option(None, '--entry-id', help='Changelog entry UUID (for approve/reject)'),
    rule_id: str = typer.Option(None, '--rule-id', help='Alert rule UUID (for update_alert/delete_alert/test_alert)'),
    webhook_url: str = typer.Option(None, '--webhook-url', help='Webhook URL (for create_alert)'),
    threshold_pct: int = typer.Option(None, '--threshold-pct', help='Spike threshold percentage (for create_alert, default 200)'),
    window_hours: int = typer.Option(None, '--window-hours', help='Detection window in hours (for create_alert)'),
    cooldown_minutes: int = typer.Option(None, '--cooldown-minutes', help='Min minutes between alerts (for create_alert, default 60)'),
    limit: int = typer.Option(None, '--limit', help='Max entries to return (for list_events/view_changelog)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for list_events)'),
):
    'Manage brand monitors and configuration. Actions: create, update, delete, run_now, create_alert, update_alert, delete_alert, test_alert, list_alerts, list_events, view_changelog, approve, reject.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'delete', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('run-now')
@handle_errors
def run_now(
    name: str = typer.Option(None, '--name', help="Monitor name (for create, e.g. 'Nike Brand Monitor')"),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to track (for create/update)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID (for update/delete/run_now/config actions)'),
    sources: str = typer.Option(None, '--sources', help='Data sources (for create/update). Default: twitter, instagram, reddit'),
    boolean_query: str = typer.Option(None, '--boolean-query', help='Advanced Boolean query for FTS (for create/update)'),
    languages: str = typer.Option(None, '--languages', help="ISO 639-1 language codes to filter by (for create/update, e.g. ['en', 'es'])"),
    regions: str = typer.Option(None, '--regions', help="ISO 3166-1 region codes to filter by (for create/update, e.g. ['US', 'GB'])"),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names for share-of-voice analysis (max 10, for create/update)'),
    is_active: bool = typer.Option(None, '--is-active', help='Enable/disable the monitor (for update)'),
    entry_id: str = typer.Option(None, '--entry-id', help='Changelog entry UUID (for approve/reject)'),
    rule_id: str = typer.Option(None, '--rule-id', help='Alert rule UUID (for update_alert/delete_alert/test_alert)'),
    webhook_url: str = typer.Option(None, '--webhook-url', help='Webhook URL (for create_alert)'),
    threshold_pct: int = typer.Option(None, '--threshold-pct', help='Spike threshold percentage (for create_alert, default 200)'),
    window_hours: int = typer.Option(None, '--window-hours', help='Detection window in hours (for create_alert)'),
    cooldown_minutes: int = typer.Option(None, '--cooldown-minutes', help='Min minutes between alerts (for create_alert, default 60)'),
    limit: int = typer.Option(None, '--limit', help='Max entries to return (for list_events/view_changelog)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for list_events)'),
):
    'Manage brand monitors and configuration. Actions: create, update, delete, run_now, create_alert, update_alert, delete_alert, test_alert, list_alerts, list_events, view_changelog, approve, reject.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'run_now', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('create-alert')
@handle_errors
def create_alert(
    name: str = typer.Option(None, '--name', help="Monitor name (for create, e.g. 'Nike Brand Monitor')"),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to track (for create/update)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID (for update/delete/run_now/config actions)'),
    sources: str = typer.Option(None, '--sources', help='Data sources (for create/update). Default: twitter, instagram, reddit'),
    boolean_query: str = typer.Option(None, '--boolean-query', help='Advanced Boolean query for FTS (for create/update)'),
    languages: str = typer.Option(None, '--languages', help="ISO 639-1 language codes to filter by (for create/update, e.g. ['en', 'es'])"),
    regions: str = typer.Option(None, '--regions', help="ISO 3166-1 region codes to filter by (for create/update, e.g. ['US', 'GB'])"),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names for share-of-voice analysis (max 10, for create/update)'),
    is_active: bool = typer.Option(None, '--is-active', help='Enable/disable the monitor (for update)'),
    entry_id: str = typer.Option(None, '--entry-id', help='Changelog entry UUID (for approve/reject)'),
    rule_id: str = typer.Option(None, '--rule-id', help='Alert rule UUID (for update_alert/delete_alert/test_alert)'),
    webhook_url: str = typer.Option(None, '--webhook-url', help='Webhook URL (for create_alert)'),
    threshold_pct: int = typer.Option(None, '--threshold-pct', help='Spike threshold percentage (for create_alert, default 200)'),
    window_hours: int = typer.Option(None, '--window-hours', help='Detection window in hours (for create_alert)'),
    cooldown_minutes: int = typer.Option(None, '--cooldown-minutes', help='Min minutes between alerts (for create_alert, default 60)'),
    limit: int = typer.Option(None, '--limit', help='Max entries to return (for list_events/view_changelog)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for list_events)'),
):
    'Manage brand monitors and configuration. Actions: create, update, delete, run_now, create_alert, update_alert, delete_alert, test_alert, list_alerts, list_events, view_changelog, approve, reject.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'create_alert', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('update-alert')
@handle_errors
def update_alert(
    name: str = typer.Option(None, '--name', help="Monitor name (for create, e.g. 'Nike Brand Monitor')"),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to track (for create/update)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID (for update/delete/run_now/config actions)'),
    sources: str = typer.Option(None, '--sources', help='Data sources (for create/update). Default: twitter, instagram, reddit'),
    boolean_query: str = typer.Option(None, '--boolean-query', help='Advanced Boolean query for FTS (for create/update)'),
    languages: str = typer.Option(None, '--languages', help="ISO 639-1 language codes to filter by (for create/update, e.g. ['en', 'es'])"),
    regions: str = typer.Option(None, '--regions', help="ISO 3166-1 region codes to filter by (for create/update, e.g. ['US', 'GB'])"),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names for share-of-voice analysis (max 10, for create/update)'),
    is_active: bool = typer.Option(None, '--is-active', help='Enable/disable the monitor (for update)'),
    entry_id: str = typer.Option(None, '--entry-id', help='Changelog entry UUID (for approve/reject)'),
    rule_id: str = typer.Option(None, '--rule-id', help='Alert rule UUID (for update_alert/delete_alert/test_alert)'),
    webhook_url: str = typer.Option(None, '--webhook-url', help='Webhook URL (for create_alert)'),
    threshold_pct: int = typer.Option(None, '--threshold-pct', help='Spike threshold percentage (for create_alert, default 200)'),
    window_hours: int = typer.Option(None, '--window-hours', help='Detection window in hours (for create_alert)'),
    cooldown_minutes: int = typer.Option(None, '--cooldown-minutes', help='Min minutes between alerts (for create_alert, default 60)'),
    limit: int = typer.Option(None, '--limit', help='Max entries to return (for list_events/view_changelog)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for list_events)'),
):
    'Manage brand monitors and configuration. Actions: create, update, delete, run_now, create_alert, update_alert, delete_alert, test_alert, list_alerts, list_events, view_changelog, approve, reject.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'update_alert', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('delete-alert')
@handle_errors
def delete_alert(
    name: str = typer.Option(None, '--name', help="Monitor name (for create, e.g. 'Nike Brand Monitor')"),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to track (for create/update)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID (for update/delete/run_now/config actions)'),
    sources: str = typer.Option(None, '--sources', help='Data sources (for create/update). Default: twitter, instagram, reddit'),
    boolean_query: str = typer.Option(None, '--boolean-query', help='Advanced Boolean query for FTS (for create/update)'),
    languages: str = typer.Option(None, '--languages', help="ISO 639-1 language codes to filter by (for create/update, e.g. ['en', 'es'])"),
    regions: str = typer.Option(None, '--regions', help="ISO 3166-1 region codes to filter by (for create/update, e.g. ['US', 'GB'])"),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names for share-of-voice analysis (max 10, for create/update)'),
    is_active: bool = typer.Option(None, '--is-active', help='Enable/disable the monitor (for update)'),
    entry_id: str = typer.Option(None, '--entry-id', help='Changelog entry UUID (for approve/reject)'),
    rule_id: str = typer.Option(None, '--rule-id', help='Alert rule UUID (for update_alert/delete_alert/test_alert)'),
    webhook_url: str = typer.Option(None, '--webhook-url', help='Webhook URL (for create_alert)'),
    threshold_pct: int = typer.Option(None, '--threshold-pct', help='Spike threshold percentage (for create_alert, default 200)'),
    window_hours: int = typer.Option(None, '--window-hours', help='Detection window in hours (for create_alert)'),
    cooldown_minutes: int = typer.Option(None, '--cooldown-minutes', help='Min minutes between alerts (for create_alert, default 60)'),
    limit: int = typer.Option(None, '--limit', help='Max entries to return (for list_events/view_changelog)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for list_events)'),
):
    'Manage brand monitors and configuration. Actions: create, update, delete, run_now, create_alert, update_alert, delete_alert, test_alert, list_alerts, list_events, view_changelog, approve, reject.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'delete_alert', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('test-alert')
@handle_errors
def test_alert(
    name: str = typer.Option(None, '--name', help="Monitor name (for create, e.g. 'Nike Brand Monitor')"),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to track (for create/update)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID (for update/delete/run_now/config actions)'),
    sources: str = typer.Option(None, '--sources', help='Data sources (for create/update). Default: twitter, instagram, reddit'),
    boolean_query: str = typer.Option(None, '--boolean-query', help='Advanced Boolean query for FTS (for create/update)'),
    languages: str = typer.Option(None, '--languages', help="ISO 639-1 language codes to filter by (for create/update, e.g. ['en', 'es'])"),
    regions: str = typer.Option(None, '--regions', help="ISO 3166-1 region codes to filter by (for create/update, e.g. ['US', 'GB'])"),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names for share-of-voice analysis (max 10, for create/update)'),
    is_active: bool = typer.Option(None, '--is-active', help='Enable/disable the monitor (for update)'),
    entry_id: str = typer.Option(None, '--entry-id', help='Changelog entry UUID (for approve/reject)'),
    rule_id: str = typer.Option(None, '--rule-id', help='Alert rule UUID (for update_alert/delete_alert/test_alert)'),
    webhook_url: str = typer.Option(None, '--webhook-url', help='Webhook URL (for create_alert)'),
    threshold_pct: int = typer.Option(None, '--threshold-pct', help='Spike threshold percentage (for create_alert, default 200)'),
    window_hours: int = typer.Option(None, '--window-hours', help='Detection window in hours (for create_alert)'),
    cooldown_minutes: int = typer.Option(None, '--cooldown-minutes', help='Min minutes between alerts (for create_alert, default 60)'),
    limit: int = typer.Option(None, '--limit', help='Max entries to return (for list_events/view_changelog)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for list_events)'),
):
    'Manage brand monitors and configuration. Actions: create, update, delete, run_now, create_alert, update_alert, delete_alert, test_alert, list_alerts, list_events, view_changelog, approve, reject.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'test_alert', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('list-alerts')
@handle_errors
def list_alerts(
    name: str = typer.Option(None, '--name', help="Monitor name (for create, e.g. 'Nike Brand Monitor')"),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to track (for create/update)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID (for update/delete/run_now/config actions)'),
    sources: str = typer.Option(None, '--sources', help='Data sources (for create/update). Default: twitter, instagram, reddit'),
    boolean_query: str = typer.Option(None, '--boolean-query', help='Advanced Boolean query for FTS (for create/update)'),
    languages: str = typer.Option(None, '--languages', help="ISO 639-1 language codes to filter by (for create/update, e.g. ['en', 'es'])"),
    regions: str = typer.Option(None, '--regions', help="ISO 3166-1 region codes to filter by (for create/update, e.g. ['US', 'GB'])"),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names for share-of-voice analysis (max 10, for create/update)'),
    is_active: bool = typer.Option(None, '--is-active', help='Enable/disable the monitor (for update)'),
    entry_id: str = typer.Option(None, '--entry-id', help='Changelog entry UUID (for approve/reject)'),
    rule_id: str = typer.Option(None, '--rule-id', help='Alert rule UUID (for update_alert/delete_alert/test_alert)'),
    webhook_url: str = typer.Option(None, '--webhook-url', help='Webhook URL (for create_alert)'),
    threshold_pct: int = typer.Option(None, '--threshold-pct', help='Spike threshold percentage (for create_alert, default 200)'),
    window_hours: int = typer.Option(None, '--window-hours', help='Detection window in hours (for create_alert)'),
    cooldown_minutes: int = typer.Option(None, '--cooldown-minutes', help='Min minutes between alerts (for create_alert, default 60)'),
    limit: int = typer.Option(None, '--limit', help='Max entries to return (for list_events/view_changelog)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for list_events)'),
):
    'Manage brand monitors and configuration. Actions: create, update, delete, run_now, create_alert, update_alert, delete_alert, test_alert, list_alerts, list_events, view_changelog, approve, reject.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'list_alerts', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('list-events')
@handle_errors
def list_events(
    name: str = typer.Option(None, '--name', help="Monitor name (for create, e.g. 'Nike Brand Monitor')"),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to track (for create/update)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID (for update/delete/run_now/config actions)'),
    sources: str = typer.Option(None, '--sources', help='Data sources (for create/update). Default: twitter, instagram, reddit'),
    boolean_query: str = typer.Option(None, '--boolean-query', help='Advanced Boolean query for FTS (for create/update)'),
    languages: str = typer.Option(None, '--languages', help="ISO 639-1 language codes to filter by (for create/update, e.g. ['en', 'es'])"),
    regions: str = typer.Option(None, '--regions', help="ISO 3166-1 region codes to filter by (for create/update, e.g. ['US', 'GB'])"),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names for share-of-voice analysis (max 10, for create/update)'),
    is_active: bool = typer.Option(None, '--is-active', help='Enable/disable the monitor (for update)'),
    entry_id: str = typer.Option(None, '--entry-id', help='Changelog entry UUID (for approve/reject)'),
    rule_id: str = typer.Option(None, '--rule-id', help='Alert rule UUID (for update_alert/delete_alert/test_alert)'),
    webhook_url: str = typer.Option(None, '--webhook-url', help='Webhook URL (for create_alert)'),
    threshold_pct: int = typer.Option(None, '--threshold-pct', help='Spike threshold percentage (for create_alert, default 200)'),
    window_hours: int = typer.Option(None, '--window-hours', help='Detection window in hours (for create_alert)'),
    cooldown_minutes: int = typer.Option(None, '--cooldown-minutes', help='Min minutes between alerts (for create_alert, default 60)'),
    limit: int = typer.Option(None, '--limit', help='Max entries to return (for list_events/view_changelog)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for list_events)'),
):
    'Manage brand monitors and configuration. Actions: create, update, delete, run_now, create_alert, update_alert, delete_alert, test_alert, list_alerts, list_events, view_changelog, approve, reject.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'list_events', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('view-changelog')
@handle_errors
def view_changelog(
    name: str = typer.Option(None, '--name', help="Monitor name (for create, e.g. 'Nike Brand Monitor')"),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to track (for create/update)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID (for update/delete/run_now/config actions)'),
    sources: str = typer.Option(None, '--sources', help='Data sources (for create/update). Default: twitter, instagram, reddit'),
    boolean_query: str = typer.Option(None, '--boolean-query', help='Advanced Boolean query for FTS (for create/update)'),
    languages: str = typer.Option(None, '--languages', help="ISO 639-1 language codes to filter by (for create/update, e.g. ['en', 'es'])"),
    regions: str = typer.Option(None, '--regions', help="ISO 3166-1 region codes to filter by (for create/update, e.g. ['US', 'GB'])"),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names for share-of-voice analysis (max 10, for create/update)'),
    is_active: bool = typer.Option(None, '--is-active', help='Enable/disable the monitor (for update)'),
    entry_id: str = typer.Option(None, '--entry-id', help='Changelog entry UUID (for approve/reject)'),
    rule_id: str = typer.Option(None, '--rule-id', help='Alert rule UUID (for update_alert/delete_alert/test_alert)'),
    webhook_url: str = typer.Option(None, '--webhook-url', help='Webhook URL (for create_alert)'),
    threshold_pct: int = typer.Option(None, '--threshold-pct', help='Spike threshold percentage (for create_alert, default 200)'),
    window_hours: int = typer.Option(None, '--window-hours', help='Detection window in hours (for create_alert)'),
    cooldown_minutes: int = typer.Option(None, '--cooldown-minutes', help='Min minutes between alerts (for create_alert, default 60)'),
    limit: int = typer.Option(None, '--limit', help='Max entries to return (for list_events/view_changelog)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for list_events)'),
):
    'Manage brand monitors and configuration. Actions: create, update, delete, run_now, create_alert, update_alert, delete_alert, test_alert, list_alerts, list_events, view_changelog, approve, reject.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'view_changelog', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('approve')
@handle_errors
def approve(
    name: str = typer.Option(None, '--name', help="Monitor name (for create, e.g. 'Nike Brand Monitor')"),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to track (for create/update)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID (for update/delete/run_now/config actions)'),
    sources: str = typer.Option(None, '--sources', help='Data sources (for create/update). Default: twitter, instagram, reddit'),
    boolean_query: str = typer.Option(None, '--boolean-query', help='Advanced Boolean query for FTS (for create/update)'),
    languages: str = typer.Option(None, '--languages', help="ISO 639-1 language codes to filter by (for create/update, e.g. ['en', 'es'])"),
    regions: str = typer.Option(None, '--regions', help="ISO 3166-1 region codes to filter by (for create/update, e.g. ['US', 'GB'])"),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names for share-of-voice analysis (max 10, for create/update)'),
    is_active: bool = typer.Option(None, '--is-active', help='Enable/disable the monitor (for update)'),
    entry_id: str = typer.Option(None, '--entry-id', help='Changelog entry UUID (for approve/reject)'),
    rule_id: str = typer.Option(None, '--rule-id', help='Alert rule UUID (for update_alert/delete_alert/test_alert)'),
    webhook_url: str = typer.Option(None, '--webhook-url', help='Webhook URL (for create_alert)'),
    threshold_pct: int = typer.Option(None, '--threshold-pct', help='Spike threshold percentage (for create_alert, default 200)'),
    window_hours: int = typer.Option(None, '--window-hours', help='Detection window in hours (for create_alert)'),
    cooldown_minutes: int = typer.Option(None, '--cooldown-minutes', help='Min minutes between alerts (for create_alert, default 60)'),
    limit: int = typer.Option(None, '--limit', help='Max entries to return (for list_events/view_changelog)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for list_events)'),
):
    'Manage brand monitors and configuration. Actions: create, update, delete, run_now, create_alert, update_alert, delete_alert, test_alert, list_alerts, list_events, view_changelog, approve, reject.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'approve', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('reject')
@handle_errors
def reject(
    name: str = typer.Option(None, '--name', help="Monitor name (for create, e.g. 'Nike Brand Monitor')"),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to track (for create/update)'),
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID (for update/delete/run_now/config actions)'),
    sources: str = typer.Option(None, '--sources', help='Data sources (for create/update). Default: twitter, instagram, reddit'),
    boolean_query: str = typer.Option(None, '--boolean-query', help='Advanced Boolean query for FTS (for create/update)'),
    languages: str = typer.Option(None, '--languages', help="ISO 639-1 language codes to filter by (for create/update, e.g. ['en', 'es'])"),
    regions: str = typer.Option(None, '--regions', help="ISO 3166-1 region codes to filter by (for create/update, e.g. ['US', 'GB'])"),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names for share-of-voice analysis (max 10, for create/update)'),
    is_active: bool = typer.Option(None, '--is-active', help='Enable/disable the monitor (for update)'),
    entry_id: str = typer.Option(None, '--entry-id', help='Changelog entry UUID (for approve/reject)'),
    rule_id: str = typer.Option(None, '--rule-id', help='Alert rule UUID (for update_alert/delete_alert/test_alert)'),
    webhook_url: str = typer.Option(None, '--webhook-url', help='Webhook URL (for create_alert)'),
    threshold_pct: int = typer.Option(None, '--threshold-pct', help='Spike threshold percentage (for create_alert, default 200)'),
    window_hours: int = typer.Option(None, '--window-hours', help='Detection window in hours (for create_alert)'),
    cooldown_minutes: int = typer.Option(None, '--cooldown-minutes', help='Min minutes between alerts (for create_alert, default 60)'),
    limit: int = typer.Option(None, '--limit', help='Max entries to return (for list_events/view_changelog)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for list_events)'),
):
    'Manage brand monitors and configuration. Actions: create, update, delete, run_now, create_alert, update_alert, delete_alert, test_alert, list_alerts, list_events, view_changelog, approve, reject.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'reject', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
