# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import manage_client as gen_manage_client
# Registration: app.add_typer(gen_manage_client.app, name='manage_client')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help='Manage agency client entities. Create clients with competitor brands/domains, update competitor lists, and configure brand context for content generation.', no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('create')
@handle_errors
def create(
    name: str = typer.Option(None, '--name', help='Client name (required for create)'),
    client_id: str = typer.Option(None, '--client-id', help='Client UUID (required for get/update)'),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names (max 20)'),
    competitor_domains: str = typer.Option(None, '--competitor-domains', help='Competitor domains (max 20)'),
    brand_context: str = typer.Option(None, '--brand-context', help='Brand voice/tone guidelines (max 10KB)'),
    auto_brief: bool = typer.Option(None, '--auto-brief', help='Enable weekly auto-generated competitive briefs'),
):
    'Manage agency client entities. Create clients with competitor brands/domains, update competitor lists, and configure brand context for content generation.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_client
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_client'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'create', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('list')
@handle_errors
def list(
    name: str = typer.Option(None, '--name', help='Client name (required for create)'),
    client_id: str = typer.Option(None, '--client-id', help='Client UUID (required for get/update)'),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names (max 20)'),
    competitor_domains: str = typer.Option(None, '--competitor-domains', help='Competitor domains (max 20)'),
    brand_context: str = typer.Option(None, '--brand-context', help='Brand voice/tone guidelines (max 10KB)'),
    auto_brief: bool = typer.Option(None, '--auto-brief', help='Enable weekly auto-generated competitive briefs'),
):
    'Manage agency client entities. Create clients with competitor brands/domains, update competitor lists, and configure brand context for content generation.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_client
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_client'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'list', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('get')
@handle_errors
def get(
    name: str = typer.Option(None, '--name', help='Client name (required for create)'),
    client_id: str = typer.Option(None, '--client-id', help='Client UUID (required for get/update)'),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names (max 20)'),
    competitor_domains: str = typer.Option(None, '--competitor-domains', help='Competitor domains (max 20)'),
    brand_context: str = typer.Option(None, '--brand-context', help='Brand voice/tone guidelines (max 10KB)'),
    auto_brief: bool = typer.Option(None, '--auto-brief', help='Enable weekly auto-generated competitive briefs'),
):
    'Manage agency client entities. Create clients with competitor brands/domains, update competitor lists, and configure brand context for content generation.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_client
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_client'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'get', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('update')
@handle_errors
def update(
    name: str = typer.Option(None, '--name', help='Client name (required for create)'),
    client_id: str = typer.Option(None, '--client-id', help='Client UUID (required for get/update)'),
    competitor_brands: str = typer.Option(None, '--competitor-brands', help='Competitor brand names (max 20)'),
    competitor_domains: str = typer.Option(None, '--competitor-domains', help='Competitor domains (max 20)'),
    brand_context: str = typer.Option(None, '--brand-context', help='Brand voice/tone guidelines (max 10KB)'),
    auto_brief: bool = typer.Option(None, '--auto-brief', help='Enable weekly auto-generated competitive briefs'),
):
    'Manage agency client entities. Create clients with competitor brands/domains, update competitor lists, and configure brand context for content generation.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_client
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_client'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'update', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
