# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import manage_policy as gen_manage_policy
# Registration: app.add_typer(gen_manage_policy.app, name='manage_policy')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help='CRUD brand safety policies and evaluate them against video analyses. Actions: create, list, get, update, delete, evaluate.', no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('create')
@handle_errors
def create(
    policy_id: str = typer.Option(None, '--policy-id', help='Policy UUID (for get/update/delete/evaluate)'),
    policy_name: str = typer.Option(None, '--policy-name', help='Policy name (for create/update)'),
    rules: str = typer.Option(None, '--rules', help='Policy rules (for create/update). Each rule specifies a moderation class to check, the maximum allowed severity, and an action.'),
    analysis_id: str = typer.Option(None, '--analysis-id', help='Analysis UUID (for evaluate)'),
):
    'CRUD brand safety policies and evaluate them against video analyses. Actions: create, list, get, update, delete, evaluate.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_policy
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_policy'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'create', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('list')
@handle_errors
def list(
    policy_id: str = typer.Option(None, '--policy-id', help='Policy UUID (for get/update/delete/evaluate)'),
    policy_name: str = typer.Option(None, '--policy-name', help='Policy name (for create/update)'),
    rules: str = typer.Option(None, '--rules', help='Policy rules (for create/update). Each rule specifies a moderation class to check, the maximum allowed severity, and an action.'),
    analysis_id: str = typer.Option(None, '--analysis-id', help='Analysis UUID (for evaluate)'),
):
    'CRUD brand safety policies and evaluate them against video analyses. Actions: create, list, get, update, delete, evaluate.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_policy
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_policy'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'list', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('get')
@handle_errors
def get(
    policy_id: str = typer.Option(None, '--policy-id', help='Policy UUID (for get/update/delete/evaluate)'),
    policy_name: str = typer.Option(None, '--policy-name', help='Policy name (for create/update)'),
    rules: str = typer.Option(None, '--rules', help='Policy rules (for create/update). Each rule specifies a moderation class to check, the maximum allowed severity, and an action.'),
    analysis_id: str = typer.Option(None, '--analysis-id', help='Analysis UUID (for evaluate)'),
):
    'CRUD brand safety policies and evaluate them against video analyses. Actions: create, list, get, update, delete, evaluate.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_policy
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_policy'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'get', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('update')
@handle_errors
def update(
    policy_id: str = typer.Option(None, '--policy-id', help='Policy UUID (for get/update/delete/evaluate)'),
    policy_name: str = typer.Option(None, '--policy-name', help='Policy name (for create/update)'),
    rules: str = typer.Option(None, '--rules', help='Policy rules (for create/update). Each rule specifies a moderation class to check, the maximum allowed severity, and an action.'),
    analysis_id: str = typer.Option(None, '--analysis-id', help='Analysis UUID (for evaluate)'),
):
    'CRUD brand safety policies and evaluate them against video analyses. Actions: create, list, get, update, delete, evaluate.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_policy
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_policy'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'update', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('delete')
@handle_errors
def delete(
    policy_id: str = typer.Option(None, '--policy-id', help='Policy UUID (for get/update/delete/evaluate)'),
    policy_name: str = typer.Option(None, '--policy-name', help='Policy name (for create/update)'),
    rules: str = typer.Option(None, '--rules', help='Policy rules (for create/update). Each rule specifies a moderation class to check, the maximum allowed severity, and an action.'),
    analysis_id: str = typer.Option(None, '--analysis-id', help='Analysis UUID (for evaluate)'),
):
    'CRUD brand safety policies and evaluate them against video analyses. Actions: create, list, get, update, delete, evaluate.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_policy
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_policy'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'delete', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('evaluate')
@handle_errors
def evaluate(
    policy_id: str = typer.Option(None, '--policy-id', help='Policy UUID (for get/update/delete/evaluate)'),
    policy_name: str = typer.Option(None, '--policy-name', help='Policy name (for create/update)'),
    rules: str = typer.Option(None, '--rules', help='Policy rules (for create/update). Each rule specifies a moderation class to check, the maximum allowed severity, and an action.'),
    analysis_id: str = typer.Option(None, '--analysis-id', help='Analysis UUID (for evaluate)'),
):
    'CRUD brand safety policies and evaluate them against video analyses. Actions: create, list, get, update, delete, evaluate.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: manage_policy
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'manage_policy'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'evaluate', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
