# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import query_monitor as gen_query_monitor
# Registration: app.add_typer(gen_query_monitor.app, name='query_monitor')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help='Query monitor data. Actions: list, search, analytics, save_to_workspace, recommend (synthesize action recommendations), classify_intent, get_runs, generate_reply.', no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('list')
@handle_errors
def list(
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID. For search, omit to use the latest active monitor.'),
    query: str = typer.Option(None, '--query', help='Full-text search query (for search/save_to_workspace)'),
    source: str = typer.Option(None, '--source', help='Filter by data source (for search/save_to_workspace)'),
    sentiment: str = typer.Option(None, '--sentiment', help='Filter by sentiment (for search/save_to_workspace)'),
    intent: str = typer.Option(None, '--intent', help='Filter by intent (for search)'),
    date_from: str = typer.Option(None, '--date-from', help='Start date ISO 8601 (for search)'),
    date_to: str = typer.Option(None, '--date-to', help='End date ISO 8601 (for search)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (for search, default: published_at)'),
    metric: str = typer.Option(None, '--metric', help='Analytics metric (for analytics action)'),
    window: str = typer.Option(None, '--window', help='Time window for analytics (default 7d)'),
    granularity: str = typer.Option(None, '--granularity', help='Time bucket granularity for sentiment_timeline (1h/6h/1d, default 1d)'),
    collection_name: str = typer.Option(None, '--collection-name', help='Name for workspace collection (for save_to_workspace)'),
    focus: str = typer.Option(None, '--focus', help="Focus area for recommend (e.g. 'negative sentiment', 'spike analysis')"),
    depth: str = typer.Option(None, '--depth', help='Recommendation depth: quick (tactical from recent mentions) or full (strategic, loads weekly digest)'),
    comment_id: str = typer.Option(None, '--comment-id', help='Comment UUID (required for generate_reply)'),
    tone: str = typer.Option(None, '--tone', help='Reply tone (for generate_reply, default: professional)'),
    max_length: int = typer.Option(None, '--max-length', help='Max reply length in characters (for generate_reply, default: 280)'),
    limit: int = typer.Option(None, '--limit', help='Results per page (default varies by action)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for search)'),
):
    'Query monitor data. Actions: list, search, analytics, save_to_workspace, recommend (synthesize action recommendations), classify_intent, get_runs, generate_reply.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: query_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'query_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'list', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('search')
@handle_errors
def search(
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID. For search, omit to use the latest active monitor.'),
    query: str = typer.Option(None, '--query', help='Full-text search query (for search/save_to_workspace)'),
    source: str = typer.Option(None, '--source', help='Filter by data source (for search/save_to_workspace)'),
    sentiment: str = typer.Option(None, '--sentiment', help='Filter by sentiment (for search/save_to_workspace)'),
    intent: str = typer.Option(None, '--intent', help='Filter by intent (for search)'),
    date_from: str = typer.Option(None, '--date-from', help='Start date ISO 8601 (for search)'),
    date_to: str = typer.Option(None, '--date-to', help='End date ISO 8601 (for search)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (for search, default: published_at)'),
    metric: str = typer.Option(None, '--metric', help='Analytics metric (for analytics action)'),
    window: str = typer.Option(None, '--window', help='Time window for analytics (default 7d)'),
    granularity: str = typer.Option(None, '--granularity', help='Time bucket granularity for sentiment_timeline (1h/6h/1d, default 1d)'),
    collection_name: str = typer.Option(None, '--collection-name', help='Name for workspace collection (for save_to_workspace)'),
    focus: str = typer.Option(None, '--focus', help="Focus area for recommend (e.g. 'negative sentiment', 'spike analysis')"),
    depth: str = typer.Option(None, '--depth', help='Recommendation depth: quick (tactical from recent mentions) or full (strategic, loads weekly digest)'),
    comment_id: str = typer.Option(None, '--comment-id', help='Comment UUID (required for generate_reply)'),
    tone: str = typer.Option(None, '--tone', help='Reply tone (for generate_reply, default: professional)'),
    max_length: int = typer.Option(None, '--max-length', help='Max reply length in characters (for generate_reply, default: 280)'),
    limit: int = typer.Option(None, '--limit', help='Results per page (default varies by action)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for search)'),
):
    'Query monitor data. Actions: list, search, analytics, save_to_workspace, recommend (synthesize action recommendations), classify_intent, get_runs, generate_reply.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: query_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'query_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'search', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('analytics')
@handle_errors
def analytics(
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID. For search, omit to use the latest active monitor.'),
    query: str = typer.Option(None, '--query', help='Full-text search query (for search/save_to_workspace)'),
    source: str = typer.Option(None, '--source', help='Filter by data source (for search/save_to_workspace)'),
    sentiment: str = typer.Option(None, '--sentiment', help='Filter by sentiment (for search/save_to_workspace)'),
    intent: str = typer.Option(None, '--intent', help='Filter by intent (for search)'),
    date_from: str = typer.Option(None, '--date-from', help='Start date ISO 8601 (for search)'),
    date_to: str = typer.Option(None, '--date-to', help='End date ISO 8601 (for search)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (for search, default: published_at)'),
    metric: str = typer.Option(None, '--metric', help='Analytics metric (for analytics action)'),
    window: str = typer.Option(None, '--window', help='Time window for analytics (default 7d)'),
    granularity: str = typer.Option(None, '--granularity', help='Time bucket granularity for sentiment_timeline (1h/6h/1d, default 1d)'),
    collection_name: str = typer.Option(None, '--collection-name', help='Name for workspace collection (for save_to_workspace)'),
    focus: str = typer.Option(None, '--focus', help="Focus area for recommend (e.g. 'negative sentiment', 'spike analysis')"),
    depth: str = typer.Option(None, '--depth', help='Recommendation depth: quick (tactical from recent mentions) or full (strategic, loads weekly digest)'),
    comment_id: str = typer.Option(None, '--comment-id', help='Comment UUID (required for generate_reply)'),
    tone: str = typer.Option(None, '--tone', help='Reply tone (for generate_reply, default: professional)'),
    max_length: int = typer.Option(None, '--max-length', help='Max reply length in characters (for generate_reply, default: 280)'),
    limit: int = typer.Option(None, '--limit', help='Results per page (default varies by action)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for search)'),
):
    'Query monitor data. Actions: list, search, analytics, save_to_workspace, recommend (synthesize action recommendations), classify_intent, get_runs, generate_reply.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: query_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'query_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'analytics', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('save-to-workspace')
@handle_errors
def save_to_workspace(
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID. For search, omit to use the latest active monitor.'),
    query: str = typer.Option(None, '--query', help='Full-text search query (for search/save_to_workspace)'),
    source: str = typer.Option(None, '--source', help='Filter by data source (for search/save_to_workspace)'),
    sentiment: str = typer.Option(None, '--sentiment', help='Filter by sentiment (for search/save_to_workspace)'),
    intent: str = typer.Option(None, '--intent', help='Filter by intent (for search)'),
    date_from: str = typer.Option(None, '--date-from', help='Start date ISO 8601 (for search)'),
    date_to: str = typer.Option(None, '--date-to', help='End date ISO 8601 (for search)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (for search, default: published_at)'),
    metric: str = typer.Option(None, '--metric', help='Analytics metric (for analytics action)'),
    window: str = typer.Option(None, '--window', help='Time window for analytics (default 7d)'),
    granularity: str = typer.Option(None, '--granularity', help='Time bucket granularity for sentiment_timeline (1h/6h/1d, default 1d)'),
    collection_name: str = typer.Option(None, '--collection-name', help='Name for workspace collection (for save_to_workspace)'),
    focus: str = typer.Option(None, '--focus', help="Focus area for recommend (e.g. 'negative sentiment', 'spike analysis')"),
    depth: str = typer.Option(None, '--depth', help='Recommendation depth: quick (tactical from recent mentions) or full (strategic, loads weekly digest)'),
    comment_id: str = typer.Option(None, '--comment-id', help='Comment UUID (required for generate_reply)'),
    tone: str = typer.Option(None, '--tone', help='Reply tone (for generate_reply, default: professional)'),
    max_length: int = typer.Option(None, '--max-length', help='Max reply length in characters (for generate_reply, default: 280)'),
    limit: int = typer.Option(None, '--limit', help='Results per page (default varies by action)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for search)'),
):
    'Query monitor data. Actions: list, search, analytics, save_to_workspace, recommend (synthesize action recommendations), classify_intent, get_runs, generate_reply.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: query_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'query_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'save_to_workspace', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('recommend')
@handle_errors
def recommend(
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID. For search, omit to use the latest active monitor.'),
    query: str = typer.Option(None, '--query', help='Full-text search query (for search/save_to_workspace)'),
    source: str = typer.Option(None, '--source', help='Filter by data source (for search/save_to_workspace)'),
    sentiment: str = typer.Option(None, '--sentiment', help='Filter by sentiment (for search/save_to_workspace)'),
    intent: str = typer.Option(None, '--intent', help='Filter by intent (for search)'),
    date_from: str = typer.Option(None, '--date-from', help='Start date ISO 8601 (for search)'),
    date_to: str = typer.Option(None, '--date-to', help='End date ISO 8601 (for search)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (for search, default: published_at)'),
    metric: str = typer.Option(None, '--metric', help='Analytics metric (for analytics action)'),
    window: str = typer.Option(None, '--window', help='Time window for analytics (default 7d)'),
    granularity: str = typer.Option(None, '--granularity', help='Time bucket granularity for sentiment_timeline (1h/6h/1d, default 1d)'),
    collection_name: str = typer.Option(None, '--collection-name', help='Name for workspace collection (for save_to_workspace)'),
    focus: str = typer.Option(None, '--focus', help="Focus area for recommend (e.g. 'negative sentiment', 'spike analysis')"),
    depth: str = typer.Option(None, '--depth', help='Recommendation depth: quick (tactical from recent mentions) or full (strategic, loads weekly digest)'),
    comment_id: str = typer.Option(None, '--comment-id', help='Comment UUID (required for generate_reply)'),
    tone: str = typer.Option(None, '--tone', help='Reply tone (for generate_reply, default: professional)'),
    max_length: int = typer.Option(None, '--max-length', help='Max reply length in characters (for generate_reply, default: 280)'),
    limit: int = typer.Option(None, '--limit', help='Results per page (default varies by action)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for search)'),
):
    'Query monitor data. Actions: list, search, analytics, save_to_workspace, recommend (synthesize action recommendations), classify_intent, get_runs, generate_reply.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: query_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'query_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'recommend', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('classify-intent')
@handle_errors
def classify_intent(
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID. For search, omit to use the latest active monitor.'),
    query: str = typer.Option(None, '--query', help='Full-text search query (for search/save_to_workspace)'),
    source: str = typer.Option(None, '--source', help='Filter by data source (for search/save_to_workspace)'),
    sentiment: str = typer.Option(None, '--sentiment', help='Filter by sentiment (for search/save_to_workspace)'),
    intent: str = typer.Option(None, '--intent', help='Filter by intent (for search)'),
    date_from: str = typer.Option(None, '--date-from', help='Start date ISO 8601 (for search)'),
    date_to: str = typer.Option(None, '--date-to', help='End date ISO 8601 (for search)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (for search, default: published_at)'),
    metric: str = typer.Option(None, '--metric', help='Analytics metric (for analytics action)'),
    window: str = typer.Option(None, '--window', help='Time window for analytics (default 7d)'),
    granularity: str = typer.Option(None, '--granularity', help='Time bucket granularity for sentiment_timeline (1h/6h/1d, default 1d)'),
    collection_name: str = typer.Option(None, '--collection-name', help='Name for workspace collection (for save_to_workspace)'),
    focus: str = typer.Option(None, '--focus', help="Focus area for recommend (e.g. 'negative sentiment', 'spike analysis')"),
    depth: str = typer.Option(None, '--depth', help='Recommendation depth: quick (tactical from recent mentions) or full (strategic, loads weekly digest)'),
    comment_id: str = typer.Option(None, '--comment-id', help='Comment UUID (required for generate_reply)'),
    tone: str = typer.Option(None, '--tone', help='Reply tone (for generate_reply, default: professional)'),
    max_length: int = typer.Option(None, '--max-length', help='Max reply length in characters (for generate_reply, default: 280)'),
    limit: int = typer.Option(None, '--limit', help='Results per page (default varies by action)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for search)'),
):
    'Query monitor data. Actions: list, search, analytics, save_to_workspace, recommend (synthesize action recommendations), classify_intent, get_runs, generate_reply.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: query_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'query_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'classify_intent', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('get-runs')
@handle_errors
def get_runs(
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID. For search, omit to use the latest active monitor.'),
    query: str = typer.Option(None, '--query', help='Full-text search query (for search/save_to_workspace)'),
    source: str = typer.Option(None, '--source', help='Filter by data source (for search/save_to_workspace)'),
    sentiment: str = typer.Option(None, '--sentiment', help='Filter by sentiment (for search/save_to_workspace)'),
    intent: str = typer.Option(None, '--intent', help='Filter by intent (for search)'),
    date_from: str = typer.Option(None, '--date-from', help='Start date ISO 8601 (for search)'),
    date_to: str = typer.Option(None, '--date-to', help='End date ISO 8601 (for search)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (for search, default: published_at)'),
    metric: str = typer.Option(None, '--metric', help='Analytics metric (for analytics action)'),
    window: str = typer.Option(None, '--window', help='Time window for analytics (default 7d)'),
    granularity: str = typer.Option(None, '--granularity', help='Time bucket granularity for sentiment_timeline (1h/6h/1d, default 1d)'),
    collection_name: str = typer.Option(None, '--collection-name', help='Name for workspace collection (for save_to_workspace)'),
    focus: str = typer.Option(None, '--focus', help="Focus area for recommend (e.g. 'negative sentiment', 'spike analysis')"),
    depth: str = typer.Option(None, '--depth', help='Recommendation depth: quick (tactical from recent mentions) or full (strategic, loads weekly digest)'),
    comment_id: str = typer.Option(None, '--comment-id', help='Comment UUID (required for generate_reply)'),
    tone: str = typer.Option(None, '--tone', help='Reply tone (for generate_reply, default: professional)'),
    max_length: int = typer.Option(None, '--max-length', help='Max reply length in characters (for generate_reply, default: 280)'),
    limit: int = typer.Option(None, '--limit', help='Results per page (default varies by action)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for search)'),
):
    'Query monitor data. Actions: list, search, analytics, save_to_workspace, recommend (synthesize action recommendations), classify_intent, get_runs, generate_reply.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: query_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'query_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'get_runs', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('generate-reply')
@handle_errors
def generate_reply(
    monitor_id: str = typer.Option(None, '--monitor-id', help='Monitor UUID. For search, omit to use the latest active monitor.'),
    query: str = typer.Option(None, '--query', help='Full-text search query (for search/save_to_workspace)'),
    source: str = typer.Option(None, '--source', help='Filter by data source (for search/save_to_workspace)'),
    sentiment: str = typer.Option(None, '--sentiment', help='Filter by sentiment (for search/save_to_workspace)'),
    intent: str = typer.Option(None, '--intent', help='Filter by intent (for search)'),
    date_from: str = typer.Option(None, '--date-from', help='Start date ISO 8601 (for search)'),
    date_to: str = typer.Option(None, '--date-to', help='End date ISO 8601 (for search)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (for search, default: published_at)'),
    metric: str = typer.Option(None, '--metric', help='Analytics metric (for analytics action)'),
    window: str = typer.Option(None, '--window', help='Time window for analytics (default 7d)'),
    granularity: str = typer.Option(None, '--granularity', help='Time bucket granularity for sentiment_timeline (1h/6h/1d, default 1d)'),
    collection_name: str = typer.Option(None, '--collection-name', help='Name for workspace collection (for save_to_workspace)'),
    focus: str = typer.Option(None, '--focus', help="Focus area for recommend (e.g. 'negative sentiment', 'spike analysis')"),
    depth: str = typer.Option(None, '--depth', help='Recommendation depth: quick (tactical from recent mentions) or full (strategic, loads weekly digest)'),
    comment_id: str = typer.Option(None, '--comment-id', help='Comment UUID (required for generate_reply)'),
    tone: str = typer.Option(None, '--tone', help='Reply tone (for generate_reply, default: professional)'),
    max_length: int = typer.Option(None, '--max-length', help='Max reply length in characters (for generate_reply, default: 280)'),
    limit: int = typer.Option(None, '--limit', help='Results per page (default varies by action)'),
    offset: int = typer.Option(None, '--offset', help='Pagination offset (for search)'),
):
    'Query monitor data. Actions: list, search, analytics, save_to_workspace, recommend (synthesize action recommendations), classify_intent, get_runs, generate_reply.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: query_monitor
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'query_monitor'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'generate_reply', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
