# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import search as gen_search
# Registration: app.add_typer(gen_search.app, name='search')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help="Unified search across content, trends, and sources. Set search_type='content' (default) for posts/videos/articles, 'trends' for platform trend data (Pro). Set action='list_sources' to see available data sources. For content: set type='posts'/'comments'/'communities', author for timeline, count_only for volume. For trends: provide platform parameter.", no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('search')
@handle_errors
def search(
    search_type: str = typer.Option(None, '--search-type', help='content (default): search posts/videos/articles. trends: get platform trends (Pro).'),
    action: str = typer.Option(None, '--action', help='Special action. list_sources: return available source metadata.'),
    client_id: str = typer.Option(None, '--client-id', help='Client UUID for scoped searches (E1).'),
    query: str = typer.Option(None, '--query', help="Search keywords in ENGLISH. Use platform-native terms (e.g. 'GRWM' not 'get ready with me video'). Required unless author is set."),
    type: str = typer.Option(None, '--type', help='posts (default): regular search. comments: Reddit comment search. communities: subreddit discovery.'),
    platforms: str = typer.Option(None, '--platforms', help='Platforms to search. Default: twitter, instagram, reddit, bluesky, news, podcasts. Add tiktok/youtube/linkedin for deeper search (requires depth=standard+).'),
    author: str = typer.Option(None, '--author', help='Get content by a specific author (username). Omit query for timeline mode.'),
    start_date: str = typer.Option(None, '--start-date', help='Start date filter (ISO format YYYY-MM-DD).'),
    end_date: str = typer.Option(None, '--end-date', help='End date filter (ISO format YYYY-MM-DD).'),
    language: str = typer.Option(None, '--language', help="Language filter (ISO 639-1 code, e.g. 'en', 'es')."),
    subreddit: str = typer.Option(None, '--subreddit', help='Filter to specific subreddit (for comments type).'),
    min_views: int = typer.Option(None, '--min-views', help='Minimum view count. ~100K for popular, ~1M for viral.'),
    min_engagement_rate: float = typer.Option(None, '--min-engagement-rate', help='Minimum engagement rate 0.0-1.0.'),
    content_format: str = typer.Option(None, '--content-format', help='short = short-form, long = long-form. Omit for all.'),
    reddit_sort: str = typer.Option(None, '--reddit-sort', help='Reddit sort order. Only applies when searching Reddit.'),
    reddit_time_range: str = typer.Option(None, '--reddit-time-range', help='Reddit time filter (for sort=top/controversial). Only applies when searching Reddit.'),
    count_only: bool = typer.Option(None, '--count-only', help='Count posts only (Twitter). Returns count instead of results.'),
    depth: str = typer.Option(None, '--depth', help='quick (<1s): social + news only. standard (<6s, default): adds TikTok/YouTube/LinkedIn. comprehensive: merges all sources.'),
    limit: int = typer.Option(None, '--limit', help='Max results (default 200). Free: up to 200, Pro: up to 2000.'),
    target_collection: str = typer.Option(None, '--target-collection', help='Workspace collection name to append results to. Omit to auto-append or create new.'),
    platform: str = typer.Option(None, '--platform', help='Platform for trends search (required when search_type=trends).'),
):
    "Unified search across content, trends, and sources. Set search_type='content' (default) for posts/videos/articles, 'trends' for platform trend data (Pro). Set action='list_sources' to see available data sources. For content: set type='posts'/'comments'/'communities', author for timeline, count_only for volume. For trends: provide platform parameter."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: search
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'search'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'search', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
