# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import seo_audit as gen_seo_audit
# Registration: app.add_typer(gen_seo_audit.app, name='seo_audit')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help="SEO and GEO audit operations. Actions: 'audit' (default): run comprehensive GEO + SEO analysis (8 credits). 'optimize': generate optimized content from a completed audit (8 credits). 'list': list past GEO audits. 'get': get specific audit by ID.", no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('audit')
@handle_errors
def audit(
    url: str = typer.Option(None, '--url', help='URL to audit (for audit action, must be HTTPS)'),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to analyze (for audit action)'),
    include: str = typer.Option(None, '--include', help='Which analyses to include (for audit action). Default: all.'),
    audit_id: str = typer.Option(None, '--audit-id', help='UUID of a GEO audit (for optimize/get actions)'),
):
    "SEO and GEO audit operations. Actions: 'audit' (default): run comprehensive GEO + SEO analysis (8 credits). 'optimize': generate optimized content from a completed audit (8 credits). 'list': list past GEO audits. 'get': get specific audit by ID."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: seo_audit
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'seo_audit'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'audit', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('optimize')
@handle_errors
def optimize(
    url: str = typer.Option(None, '--url', help='URL to audit (for audit action, must be HTTPS)'),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to analyze (for audit action)'),
    include: str = typer.Option(None, '--include', help='Which analyses to include (for audit action). Default: all.'),
    audit_id: str = typer.Option(None, '--audit-id', help='UUID of a GEO audit (for optimize/get actions)'),
):
    "SEO and GEO audit operations. Actions: 'audit' (default): run comprehensive GEO + SEO analysis (8 credits). 'optimize': generate optimized content from a completed audit (8 credits). 'list': list past GEO audits. 'get': get specific audit by ID."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: seo_audit
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'seo_audit'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'optimize', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('list')
@handle_errors
def list(
    url: str = typer.Option(None, '--url', help='URL to audit (for audit action, must be HTTPS)'),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to analyze (for audit action)'),
    include: str = typer.Option(None, '--include', help='Which analyses to include (for audit action). Default: all.'),
    audit_id: str = typer.Option(None, '--audit-id', help='UUID of a GEO audit (for optimize/get actions)'),
):
    "SEO and GEO audit operations. Actions: 'audit' (default): run comprehensive GEO + SEO analysis (8 credits). 'optimize': generate optimized content from a completed audit (8 credits). 'list': list past GEO audits. 'get': get specific audit by ID."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: seo_audit
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'seo_audit'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'list', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('get')
@handle_errors
def get(
    url: str = typer.Option(None, '--url', help='URL to audit (for audit action, must be HTTPS)'),
    keywords: str = typer.Option(None, '--keywords', help='Comma-separated keywords to analyze (for audit action)'),
    include: str = typer.Option(None, '--include', help='Which analyses to include (for audit action). Default: all.'),
    audit_id: str = typer.Option(None, '--audit-id', help='UUID of a GEO audit (for optimize/get actions)'),
):
    "SEO and GEO audit operations. Actions: 'audit' (default): run comprehensive GEO + SEO analysis (8 credits). 'optimize': generate optimized content from a completed audit (8 credits). 'list': list past GEO audits. 'get': get specific audit by ID."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: seo_audit
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'seo_audit'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'get', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
