# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import video_project as gen_video_project
# Registration: app.add_typer(gen_video_project.app, name='video_project')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help="Manage video project lifecycle. Actions: 'get' (retrieve project), 'create_storyboard' (create from a brief or analysis), 'edit_scene' (modify scene text/duration), 'reorder' (reorder scenes), 'add_references' (add reference videos), 'recompose' (recompose project after edits), 'plan_stories' (plan story sequences), 'delete_scene' (remove a scene), 'get_transcript' (view timestamped transcript), 'clean_transcript' (remove filler words). Use video_generate for preview, rendering, and job management.", no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('get')
@handle_errors
def get(
    project_id: str = typer.Option(None, '--project-id', help='Project UUID (for get/edit_scene/reorder/add_references/recompose/delete_scene)'),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Optional comma-separated analysis UUIDs (for create_storyboard inspiration)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for create_storyboard)'),
    style: str = typer.Option(None, '--style', help='Visual style (for create_storyboard)'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for edit_scene)'),
    new_prompt: str = typer.Option(None, '--new-prompt', help='New scene description (for edit_scene)'),
    new_duration: str = typer.Option(None, '--new-duration', help='New duration in seconds (for edit_scene)'),
    new_transition: str = typer.Option(None, '--new-transition', help='New transition type (for edit_scene)'),
    new_title: str = typer.Option(None, '--new-title', help='New scene title (for edit_scene)'),
    new_summary: str = typer.Option(None, '--new-summary', help='New scene summary (for edit_scene)'),
    new_caption: str = typer.Option(None, '--new-caption', help='New scene caption (for edit_scene)'),
    approve_preview: str = typer.Option(None, '--approve-preview', help="Set to 'true' to approve preview (for edit_scene)"),
    composition_spec: str = typer.Option(None, '--composition-spec', help='JSON composition spec (for legacy edit_scene without project_id)'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene UUID (for edit_scene/delete_scene)'),
    scene_ids: str = typer.Option(None, '--scene-ids', help='Comma-separated scene UUIDs in desired order (for reorder)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for reorder/add_references/recompose)'),
    context: str = typer.Option(None, '--context', help='Full creative brief / story plan JSON to guide storyboard generation'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Deprecated: use video_generate. Set to 'true' to preview all remaining scenes"),
    model: str = typer.Option(None, '--model', help='Deprecated: use video_generate. Image model to use'),
    job_id: str = typer.Option(None, '--job-id', help='Deprecated: use video_generate. Job UUID (for job_status/job_cancel)'),
    status: str = typer.Option(None, '--status', help='Deprecated: use video_generate. Filter by status'),
    limit: int = typer.Option(None, '--limit', help='Deprecated: use video_generate. Max results'),
):
    "Manage video project lifecycle. Actions: 'get' (retrieve project), 'create_storyboard' (create from a brief or analysis), 'edit_scene' (modify scene text/duration), 'reorder' (reorder scenes), 'add_references' (add reference videos), 'recompose' (recompose project after edits), 'plan_stories' (plan story sequences), 'delete_scene' (remove a scene), 'get_transcript' (view timestamped transcript), 'clean_transcript' (remove filler words). Use video_generate for preview, rendering, and job management."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_project
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_project'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'get', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('create-storyboard')
@handle_errors
def create_storyboard(
    project_id: str = typer.Option(None, '--project-id', help='Project UUID (for get/edit_scene/reorder/add_references/recompose/delete_scene)'),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Optional comma-separated analysis UUIDs (for create_storyboard inspiration)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for create_storyboard)'),
    style: str = typer.Option(None, '--style', help='Visual style (for create_storyboard)'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for edit_scene)'),
    new_prompt: str = typer.Option(None, '--new-prompt', help='New scene description (for edit_scene)'),
    new_duration: str = typer.Option(None, '--new-duration', help='New duration in seconds (for edit_scene)'),
    new_transition: str = typer.Option(None, '--new-transition', help='New transition type (for edit_scene)'),
    new_title: str = typer.Option(None, '--new-title', help='New scene title (for edit_scene)'),
    new_summary: str = typer.Option(None, '--new-summary', help='New scene summary (for edit_scene)'),
    new_caption: str = typer.Option(None, '--new-caption', help='New scene caption (for edit_scene)'),
    approve_preview: str = typer.Option(None, '--approve-preview', help="Set to 'true' to approve preview (for edit_scene)"),
    composition_spec: str = typer.Option(None, '--composition-spec', help='JSON composition spec (for legacy edit_scene without project_id)'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene UUID (for edit_scene/delete_scene)'),
    scene_ids: str = typer.Option(None, '--scene-ids', help='Comma-separated scene UUIDs in desired order (for reorder)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for reorder/add_references/recompose)'),
    context: str = typer.Option(None, '--context', help='Full creative brief / story plan JSON to guide storyboard generation'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Deprecated: use video_generate. Set to 'true' to preview all remaining scenes"),
    model: str = typer.Option(None, '--model', help='Deprecated: use video_generate. Image model to use'),
    job_id: str = typer.Option(None, '--job-id', help='Deprecated: use video_generate. Job UUID (for job_status/job_cancel)'),
    status: str = typer.Option(None, '--status', help='Deprecated: use video_generate. Filter by status'),
    limit: int = typer.Option(None, '--limit', help='Deprecated: use video_generate. Max results'),
):
    "Manage video project lifecycle. Actions: 'get' (retrieve project), 'create_storyboard' (create from a brief or analysis), 'edit_scene' (modify scene text/duration), 'reorder' (reorder scenes), 'add_references' (add reference videos), 'recompose' (recompose project after edits), 'plan_stories' (plan story sequences), 'delete_scene' (remove a scene), 'get_transcript' (view timestamped transcript), 'clean_transcript' (remove filler words). Use video_generate for preview, rendering, and job management."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_project
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_project'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'create_storyboard', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('edit-scene')
@handle_errors
def edit_scene(
    project_id: str = typer.Option(None, '--project-id', help='Project UUID (for get/edit_scene/reorder/add_references/recompose/delete_scene)'),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Optional comma-separated analysis UUIDs (for create_storyboard inspiration)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for create_storyboard)'),
    style: str = typer.Option(None, '--style', help='Visual style (for create_storyboard)'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for edit_scene)'),
    new_prompt: str = typer.Option(None, '--new-prompt', help='New scene description (for edit_scene)'),
    new_duration: str = typer.Option(None, '--new-duration', help='New duration in seconds (for edit_scene)'),
    new_transition: str = typer.Option(None, '--new-transition', help='New transition type (for edit_scene)'),
    new_title: str = typer.Option(None, '--new-title', help='New scene title (for edit_scene)'),
    new_summary: str = typer.Option(None, '--new-summary', help='New scene summary (for edit_scene)'),
    new_caption: str = typer.Option(None, '--new-caption', help='New scene caption (for edit_scene)'),
    approve_preview: str = typer.Option(None, '--approve-preview', help="Set to 'true' to approve preview (for edit_scene)"),
    composition_spec: str = typer.Option(None, '--composition-spec', help='JSON composition spec (for legacy edit_scene without project_id)'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene UUID (for edit_scene/delete_scene)'),
    scene_ids: str = typer.Option(None, '--scene-ids', help='Comma-separated scene UUIDs in desired order (for reorder)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for reorder/add_references/recompose)'),
    context: str = typer.Option(None, '--context', help='Full creative brief / story plan JSON to guide storyboard generation'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Deprecated: use video_generate. Set to 'true' to preview all remaining scenes"),
    model: str = typer.Option(None, '--model', help='Deprecated: use video_generate. Image model to use'),
    job_id: str = typer.Option(None, '--job-id', help='Deprecated: use video_generate. Job UUID (for job_status/job_cancel)'),
    status: str = typer.Option(None, '--status', help='Deprecated: use video_generate. Filter by status'),
    limit: int = typer.Option(None, '--limit', help='Deprecated: use video_generate. Max results'),
):
    "Manage video project lifecycle. Actions: 'get' (retrieve project), 'create_storyboard' (create from a brief or analysis), 'edit_scene' (modify scene text/duration), 'reorder' (reorder scenes), 'add_references' (add reference videos), 'recompose' (recompose project after edits), 'plan_stories' (plan story sequences), 'delete_scene' (remove a scene), 'get_transcript' (view timestamped transcript), 'clean_transcript' (remove filler words). Use video_generate for preview, rendering, and job management."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_project
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_project'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'edit_scene', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('reorder')
@handle_errors
def reorder(
    project_id: str = typer.Option(None, '--project-id', help='Project UUID (for get/edit_scene/reorder/add_references/recompose/delete_scene)'),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Optional comma-separated analysis UUIDs (for create_storyboard inspiration)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for create_storyboard)'),
    style: str = typer.Option(None, '--style', help='Visual style (for create_storyboard)'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for edit_scene)'),
    new_prompt: str = typer.Option(None, '--new-prompt', help='New scene description (for edit_scene)'),
    new_duration: str = typer.Option(None, '--new-duration', help='New duration in seconds (for edit_scene)'),
    new_transition: str = typer.Option(None, '--new-transition', help='New transition type (for edit_scene)'),
    new_title: str = typer.Option(None, '--new-title', help='New scene title (for edit_scene)'),
    new_summary: str = typer.Option(None, '--new-summary', help='New scene summary (for edit_scene)'),
    new_caption: str = typer.Option(None, '--new-caption', help='New scene caption (for edit_scene)'),
    approve_preview: str = typer.Option(None, '--approve-preview', help="Set to 'true' to approve preview (for edit_scene)"),
    composition_spec: str = typer.Option(None, '--composition-spec', help='JSON composition spec (for legacy edit_scene without project_id)'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene UUID (for edit_scene/delete_scene)'),
    scene_ids: str = typer.Option(None, '--scene-ids', help='Comma-separated scene UUIDs in desired order (for reorder)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for reorder/add_references/recompose)'),
    context: str = typer.Option(None, '--context', help='Full creative brief / story plan JSON to guide storyboard generation'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Deprecated: use video_generate. Set to 'true' to preview all remaining scenes"),
    model: str = typer.Option(None, '--model', help='Deprecated: use video_generate. Image model to use'),
    job_id: str = typer.Option(None, '--job-id', help='Deprecated: use video_generate. Job UUID (for job_status/job_cancel)'),
    status: str = typer.Option(None, '--status', help='Deprecated: use video_generate. Filter by status'),
    limit: int = typer.Option(None, '--limit', help='Deprecated: use video_generate. Max results'),
):
    "Manage video project lifecycle. Actions: 'get' (retrieve project), 'create_storyboard' (create from a brief or analysis), 'edit_scene' (modify scene text/duration), 'reorder' (reorder scenes), 'add_references' (add reference videos), 'recompose' (recompose project after edits), 'plan_stories' (plan story sequences), 'delete_scene' (remove a scene), 'get_transcript' (view timestamped transcript), 'clean_transcript' (remove filler words). Use video_generate for preview, rendering, and job management."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_project
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_project'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'reorder', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('add-references')
@handle_errors
def add_references(
    project_id: str = typer.Option(None, '--project-id', help='Project UUID (for get/edit_scene/reorder/add_references/recompose/delete_scene)'),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Optional comma-separated analysis UUIDs (for create_storyboard inspiration)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for create_storyboard)'),
    style: str = typer.Option(None, '--style', help='Visual style (for create_storyboard)'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for edit_scene)'),
    new_prompt: str = typer.Option(None, '--new-prompt', help='New scene description (for edit_scene)'),
    new_duration: str = typer.Option(None, '--new-duration', help='New duration in seconds (for edit_scene)'),
    new_transition: str = typer.Option(None, '--new-transition', help='New transition type (for edit_scene)'),
    new_title: str = typer.Option(None, '--new-title', help='New scene title (for edit_scene)'),
    new_summary: str = typer.Option(None, '--new-summary', help='New scene summary (for edit_scene)'),
    new_caption: str = typer.Option(None, '--new-caption', help='New scene caption (for edit_scene)'),
    approve_preview: str = typer.Option(None, '--approve-preview', help="Set to 'true' to approve preview (for edit_scene)"),
    composition_spec: str = typer.Option(None, '--composition-spec', help='JSON composition spec (for legacy edit_scene without project_id)'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene UUID (for edit_scene/delete_scene)'),
    scene_ids: str = typer.Option(None, '--scene-ids', help='Comma-separated scene UUIDs in desired order (for reorder)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for reorder/add_references/recompose)'),
    context: str = typer.Option(None, '--context', help='Full creative brief / story plan JSON to guide storyboard generation'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Deprecated: use video_generate. Set to 'true' to preview all remaining scenes"),
    model: str = typer.Option(None, '--model', help='Deprecated: use video_generate. Image model to use'),
    job_id: str = typer.Option(None, '--job-id', help='Deprecated: use video_generate. Job UUID (for job_status/job_cancel)'),
    status: str = typer.Option(None, '--status', help='Deprecated: use video_generate. Filter by status'),
    limit: int = typer.Option(None, '--limit', help='Deprecated: use video_generate. Max results'),
):
    "Manage video project lifecycle. Actions: 'get' (retrieve project), 'create_storyboard' (create from a brief or analysis), 'edit_scene' (modify scene text/duration), 'reorder' (reorder scenes), 'add_references' (add reference videos), 'recompose' (recompose project after edits), 'plan_stories' (plan story sequences), 'delete_scene' (remove a scene), 'get_transcript' (view timestamped transcript), 'clean_transcript' (remove filler words). Use video_generate for preview, rendering, and job management."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_project
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_project'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'add_references', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('recompose')
@handle_errors
def recompose(
    project_id: str = typer.Option(None, '--project-id', help='Project UUID (for get/edit_scene/reorder/add_references/recompose/delete_scene)'),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Optional comma-separated analysis UUIDs (for create_storyboard inspiration)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for create_storyboard)'),
    style: str = typer.Option(None, '--style', help='Visual style (for create_storyboard)'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for edit_scene)'),
    new_prompt: str = typer.Option(None, '--new-prompt', help='New scene description (for edit_scene)'),
    new_duration: str = typer.Option(None, '--new-duration', help='New duration in seconds (for edit_scene)'),
    new_transition: str = typer.Option(None, '--new-transition', help='New transition type (for edit_scene)'),
    new_title: str = typer.Option(None, '--new-title', help='New scene title (for edit_scene)'),
    new_summary: str = typer.Option(None, '--new-summary', help='New scene summary (for edit_scene)'),
    new_caption: str = typer.Option(None, '--new-caption', help='New scene caption (for edit_scene)'),
    approve_preview: str = typer.Option(None, '--approve-preview', help="Set to 'true' to approve preview (for edit_scene)"),
    composition_spec: str = typer.Option(None, '--composition-spec', help='JSON composition spec (for legacy edit_scene without project_id)'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene UUID (for edit_scene/delete_scene)'),
    scene_ids: str = typer.Option(None, '--scene-ids', help='Comma-separated scene UUIDs in desired order (for reorder)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for reorder/add_references/recompose)'),
    context: str = typer.Option(None, '--context', help='Full creative brief / story plan JSON to guide storyboard generation'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Deprecated: use video_generate. Set to 'true' to preview all remaining scenes"),
    model: str = typer.Option(None, '--model', help='Deprecated: use video_generate. Image model to use'),
    job_id: str = typer.Option(None, '--job-id', help='Deprecated: use video_generate. Job UUID (for job_status/job_cancel)'),
    status: str = typer.Option(None, '--status', help='Deprecated: use video_generate. Filter by status'),
    limit: int = typer.Option(None, '--limit', help='Deprecated: use video_generate. Max results'),
):
    "Manage video project lifecycle. Actions: 'get' (retrieve project), 'create_storyboard' (create from a brief or analysis), 'edit_scene' (modify scene text/duration), 'reorder' (reorder scenes), 'add_references' (add reference videos), 'recompose' (recompose project after edits), 'plan_stories' (plan story sequences), 'delete_scene' (remove a scene), 'get_transcript' (view timestamped transcript), 'clean_transcript' (remove filler words). Use video_generate for preview, rendering, and job management."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_project
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_project'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'recompose', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('plan-stories')
@handle_errors
def plan_stories(
    project_id: str = typer.Option(None, '--project-id', help='Project UUID (for get/edit_scene/reorder/add_references/recompose/delete_scene)'),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Optional comma-separated analysis UUIDs (for create_storyboard inspiration)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for create_storyboard)'),
    style: str = typer.Option(None, '--style', help='Visual style (for create_storyboard)'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for edit_scene)'),
    new_prompt: str = typer.Option(None, '--new-prompt', help='New scene description (for edit_scene)'),
    new_duration: str = typer.Option(None, '--new-duration', help='New duration in seconds (for edit_scene)'),
    new_transition: str = typer.Option(None, '--new-transition', help='New transition type (for edit_scene)'),
    new_title: str = typer.Option(None, '--new-title', help='New scene title (for edit_scene)'),
    new_summary: str = typer.Option(None, '--new-summary', help='New scene summary (for edit_scene)'),
    new_caption: str = typer.Option(None, '--new-caption', help='New scene caption (for edit_scene)'),
    approve_preview: str = typer.Option(None, '--approve-preview', help="Set to 'true' to approve preview (for edit_scene)"),
    composition_spec: str = typer.Option(None, '--composition-spec', help='JSON composition spec (for legacy edit_scene without project_id)'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene UUID (for edit_scene/delete_scene)'),
    scene_ids: str = typer.Option(None, '--scene-ids', help='Comma-separated scene UUIDs in desired order (for reorder)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for reorder/add_references/recompose)'),
    context: str = typer.Option(None, '--context', help='Full creative brief / story plan JSON to guide storyboard generation'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Deprecated: use video_generate. Set to 'true' to preview all remaining scenes"),
    model: str = typer.Option(None, '--model', help='Deprecated: use video_generate. Image model to use'),
    job_id: str = typer.Option(None, '--job-id', help='Deprecated: use video_generate. Job UUID (for job_status/job_cancel)'),
    status: str = typer.Option(None, '--status', help='Deprecated: use video_generate. Filter by status'),
    limit: int = typer.Option(None, '--limit', help='Deprecated: use video_generate. Max results'),
):
    "Manage video project lifecycle. Actions: 'get' (retrieve project), 'create_storyboard' (create from a brief or analysis), 'edit_scene' (modify scene text/duration), 'reorder' (reorder scenes), 'add_references' (add reference videos), 'recompose' (recompose project after edits), 'plan_stories' (plan story sequences), 'delete_scene' (remove a scene), 'get_transcript' (view timestamped transcript), 'clean_transcript' (remove filler words). Use video_generate for preview, rendering, and job management."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_project
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_project'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'plan_stories', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('delete-scene')
@handle_errors
def delete_scene(
    project_id: str = typer.Option(None, '--project-id', help='Project UUID (for get/edit_scene/reorder/add_references/recompose/delete_scene)'),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Optional comma-separated analysis UUIDs (for create_storyboard inspiration)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for create_storyboard)'),
    style: str = typer.Option(None, '--style', help='Visual style (for create_storyboard)'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for edit_scene)'),
    new_prompt: str = typer.Option(None, '--new-prompt', help='New scene description (for edit_scene)'),
    new_duration: str = typer.Option(None, '--new-duration', help='New duration in seconds (for edit_scene)'),
    new_transition: str = typer.Option(None, '--new-transition', help='New transition type (for edit_scene)'),
    new_title: str = typer.Option(None, '--new-title', help='New scene title (for edit_scene)'),
    new_summary: str = typer.Option(None, '--new-summary', help='New scene summary (for edit_scene)'),
    new_caption: str = typer.Option(None, '--new-caption', help='New scene caption (for edit_scene)'),
    approve_preview: str = typer.Option(None, '--approve-preview', help="Set to 'true' to approve preview (for edit_scene)"),
    composition_spec: str = typer.Option(None, '--composition-spec', help='JSON composition spec (for legacy edit_scene without project_id)'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene UUID (for edit_scene/delete_scene)'),
    scene_ids: str = typer.Option(None, '--scene-ids', help='Comma-separated scene UUIDs in desired order (for reorder)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for reorder/add_references/recompose)'),
    context: str = typer.Option(None, '--context', help='Full creative brief / story plan JSON to guide storyboard generation'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Deprecated: use video_generate. Set to 'true' to preview all remaining scenes"),
    model: str = typer.Option(None, '--model', help='Deprecated: use video_generate. Image model to use'),
    job_id: str = typer.Option(None, '--job-id', help='Deprecated: use video_generate. Job UUID (for job_status/job_cancel)'),
    status: str = typer.Option(None, '--status', help='Deprecated: use video_generate. Filter by status'),
    limit: int = typer.Option(None, '--limit', help='Deprecated: use video_generate. Max results'),
):
    "Manage video project lifecycle. Actions: 'get' (retrieve project), 'create_storyboard' (create from a brief or analysis), 'edit_scene' (modify scene text/duration), 'reorder' (reorder scenes), 'add_references' (add reference videos), 'recompose' (recompose project after edits), 'plan_stories' (plan story sequences), 'delete_scene' (remove a scene), 'get_transcript' (view timestamped transcript), 'clean_transcript' (remove filler words). Use video_generate for preview, rendering, and job management."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_project
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_project'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'delete_scene', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('get-transcript')
@handle_errors
def get_transcript(
    project_id: str = typer.Option(None, '--project-id', help='Project UUID (for get/edit_scene/reorder/add_references/recompose/delete_scene)'),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Optional comma-separated analysis UUIDs (for create_storyboard inspiration)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for create_storyboard)'),
    style: str = typer.Option(None, '--style', help='Visual style (for create_storyboard)'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for edit_scene)'),
    new_prompt: str = typer.Option(None, '--new-prompt', help='New scene description (for edit_scene)'),
    new_duration: str = typer.Option(None, '--new-duration', help='New duration in seconds (for edit_scene)'),
    new_transition: str = typer.Option(None, '--new-transition', help='New transition type (for edit_scene)'),
    new_title: str = typer.Option(None, '--new-title', help='New scene title (for edit_scene)'),
    new_summary: str = typer.Option(None, '--new-summary', help='New scene summary (for edit_scene)'),
    new_caption: str = typer.Option(None, '--new-caption', help='New scene caption (for edit_scene)'),
    approve_preview: str = typer.Option(None, '--approve-preview', help="Set to 'true' to approve preview (for edit_scene)"),
    composition_spec: str = typer.Option(None, '--composition-spec', help='JSON composition spec (for legacy edit_scene without project_id)'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene UUID (for edit_scene/delete_scene)'),
    scene_ids: str = typer.Option(None, '--scene-ids', help='Comma-separated scene UUIDs in desired order (for reorder)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for reorder/add_references/recompose)'),
    context: str = typer.Option(None, '--context', help='Full creative brief / story plan JSON to guide storyboard generation'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Deprecated: use video_generate. Set to 'true' to preview all remaining scenes"),
    model: str = typer.Option(None, '--model', help='Deprecated: use video_generate. Image model to use'),
    job_id: str = typer.Option(None, '--job-id', help='Deprecated: use video_generate. Job UUID (for job_status/job_cancel)'),
    status: str = typer.Option(None, '--status', help='Deprecated: use video_generate. Filter by status'),
    limit: int = typer.Option(None, '--limit', help='Deprecated: use video_generate. Max results'),
):
    "Manage video project lifecycle. Actions: 'get' (retrieve project), 'create_storyboard' (create from a brief or analysis), 'edit_scene' (modify scene text/duration), 'reorder' (reorder scenes), 'add_references' (add reference videos), 'recompose' (recompose project after edits), 'plan_stories' (plan story sequences), 'delete_scene' (remove a scene), 'get_transcript' (view timestamped transcript), 'clean_transcript' (remove filler words). Use video_generate for preview, rendering, and job management."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_project
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_project'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'get_transcript', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('clean-transcript')
@handle_errors
def clean_transcript(
    project_id: str = typer.Option(None, '--project-id', help='Project UUID (for get/edit_scene/reorder/add_references/recompose/delete_scene)'),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Optional comma-separated analysis UUIDs (for create_storyboard inspiration)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for create_storyboard)'),
    style: str = typer.Option(None, '--style', help='Visual style (for create_storyboard)'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for edit_scene)'),
    new_prompt: str = typer.Option(None, '--new-prompt', help='New scene description (for edit_scene)'),
    new_duration: str = typer.Option(None, '--new-duration', help='New duration in seconds (for edit_scene)'),
    new_transition: str = typer.Option(None, '--new-transition', help='New transition type (for edit_scene)'),
    new_title: str = typer.Option(None, '--new-title', help='New scene title (for edit_scene)'),
    new_summary: str = typer.Option(None, '--new-summary', help='New scene summary (for edit_scene)'),
    new_caption: str = typer.Option(None, '--new-caption', help='New scene caption (for edit_scene)'),
    approve_preview: str = typer.Option(None, '--approve-preview', help="Set to 'true' to approve preview (for edit_scene)"),
    composition_spec: str = typer.Option(None, '--composition-spec', help='JSON composition spec (for legacy edit_scene without project_id)'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene UUID (for edit_scene/delete_scene)'),
    scene_ids: str = typer.Option(None, '--scene-ids', help='Comma-separated scene UUIDs in desired order (for reorder)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for reorder/add_references/recompose)'),
    context: str = typer.Option(None, '--context', help='Full creative brief / story plan JSON to guide storyboard generation'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Deprecated: use video_generate. Set to 'true' to preview all remaining scenes"),
    model: str = typer.Option(None, '--model', help='Deprecated: use video_generate. Image model to use'),
    job_id: str = typer.Option(None, '--job-id', help='Deprecated: use video_generate. Job UUID (for job_status/job_cancel)'),
    status: str = typer.Option(None, '--status', help='Deprecated: use video_generate. Filter by status'),
    limit: int = typer.Option(None, '--limit', help='Deprecated: use video_generate. Max results'),
):
    "Manage video project lifecycle. Actions: 'get' (retrieve project), 'create_storyboard' (create from a brief or analysis), 'edit_scene' (modify scene text/duration), 'reorder' (reorder scenes), 'add_references' (add reference videos), 'recompose' (recompose project after edits), 'plan_stories' (plan story sequences), 'delete_scene' (remove a scene), 'get_transcript' (view timestamped transcript), 'clean_transcript' (remove filler words). Use video_generate for preview, rendering, and job management."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_project
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_project'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'clean_transcript', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
