# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import video_generate as gen_video_generate
# Registration: app.add_typer(gen_video_generate.app, name='video_generate')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help='Generate videos, preview storyboards, verify quality, and manage rendering jobs. Use video_project for project creation and editing.', no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('preview')
@handle_errors
def preview(
    project_id: str = typer.Option(None, '--project-id', help='Video project ID'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene ID for regenerate'),
    model: str = typer.Option(None, '--model', help='Model to use for generation'),
    job_id: str = typer.Option(None, '--job-id', help='Job ID for status/cancel'),
    status: str = typer.Option(None, '--status', help='Filter jobs by status'),
    limit: int = typer.Option(None, '--limit', help='Max jobs to return'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for preview/verify)'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Set to 'true' to preview all remaining scenes (for preview)"),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Comma-separated analysis UUIDs (for generate)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for generate)'),
    style: str = typer.Option(None, '--style', help='Visual style (for generate)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for regenerate)'),
):
    'Generate videos, preview storyboards, verify quality, and manage rendering jobs. Use video_project for project creation and editing.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_generate
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_generate'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'preview', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('verify')
@handle_errors
def verify(
    project_id: str = typer.Option(None, '--project-id', help='Video project ID'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene ID for regenerate'),
    model: str = typer.Option(None, '--model', help='Model to use for generation'),
    job_id: str = typer.Option(None, '--job-id', help='Job ID for status/cancel'),
    status: str = typer.Option(None, '--status', help='Filter jobs by status'),
    limit: int = typer.Option(None, '--limit', help='Max jobs to return'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for preview/verify)'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Set to 'true' to preview all remaining scenes (for preview)"),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Comma-separated analysis UUIDs (for generate)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for generate)'),
    style: str = typer.Option(None, '--style', help='Visual style (for generate)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for regenerate)'),
):
    'Generate videos, preview storyboards, verify quality, and manage rendering jobs. Use video_project for project creation and editing.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_generate
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_generate'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'verify', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('generate')
@handle_errors
def generate(
    project_id: str = typer.Option(None, '--project-id', help='Video project ID'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene ID for regenerate'),
    model: str = typer.Option(None, '--model', help='Model to use for generation'),
    job_id: str = typer.Option(None, '--job-id', help='Job ID for status/cancel'),
    status: str = typer.Option(None, '--status', help='Filter jobs by status'),
    limit: int = typer.Option(None, '--limit', help='Max jobs to return'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for preview/verify)'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Set to 'true' to preview all remaining scenes (for preview)"),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Comma-separated analysis UUIDs (for generate)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for generate)'),
    style: str = typer.Option(None, '--style', help='Visual style (for generate)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for regenerate)'),
):
    'Generate videos, preview storyboards, verify quality, and manage rendering jobs. Use video_project for project creation and editing.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_generate
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_generate'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'generate', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('regenerate')
@handle_errors
def regenerate(
    project_id: str = typer.Option(None, '--project-id', help='Video project ID'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene ID for regenerate'),
    model: str = typer.Option(None, '--model', help='Model to use for generation'),
    job_id: str = typer.Option(None, '--job-id', help='Job ID for status/cancel'),
    status: str = typer.Option(None, '--status', help='Filter jobs by status'),
    limit: int = typer.Option(None, '--limit', help='Max jobs to return'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for preview/verify)'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Set to 'true' to preview all remaining scenes (for preview)"),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Comma-separated analysis UUIDs (for generate)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for generate)'),
    style: str = typer.Option(None, '--style', help='Visual style (for generate)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for regenerate)'),
):
    'Generate videos, preview storyboards, verify quality, and manage rendering jobs. Use video_project for project creation and editing.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_generate
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_generate'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'regenerate', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('job-status')
@handle_errors
def job_status(
    project_id: str = typer.Option(None, '--project-id', help='Video project ID'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene ID for regenerate'),
    model: str = typer.Option(None, '--model', help='Model to use for generation'),
    job_id: str = typer.Option(None, '--job-id', help='Job ID for status/cancel'),
    status: str = typer.Option(None, '--status', help='Filter jobs by status'),
    limit: int = typer.Option(None, '--limit', help='Max jobs to return'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for preview/verify)'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Set to 'true' to preview all remaining scenes (for preview)"),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Comma-separated analysis UUIDs (for generate)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for generate)'),
    style: str = typer.Option(None, '--style', help='Visual style (for generate)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for regenerate)'),
):
    'Generate videos, preview storyboards, verify quality, and manage rendering jobs. Use video_project for project creation and editing.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_generate
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_generate'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'job_status', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('job-cancel')
@handle_errors
def job_cancel(
    project_id: str = typer.Option(None, '--project-id', help='Video project ID'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene ID for regenerate'),
    model: str = typer.Option(None, '--model', help='Model to use for generation'),
    job_id: str = typer.Option(None, '--job-id', help='Job ID for status/cancel'),
    status: str = typer.Option(None, '--status', help='Filter jobs by status'),
    limit: int = typer.Option(None, '--limit', help='Max jobs to return'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for preview/verify)'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Set to 'true' to preview all remaining scenes (for preview)"),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Comma-separated analysis UUIDs (for generate)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for generate)'),
    style: str = typer.Option(None, '--style', help='Visual style (for generate)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for regenerate)'),
):
    'Generate videos, preview storyboards, verify quality, and manage rendering jobs. Use video_project for project creation and editing.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_generate
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_generate'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'job_cancel', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('job-list')
@handle_errors
def job_list(
    project_id: str = typer.Option(None, '--project-id', help='Video project ID'),
    scene_id: str = typer.Option(None, '--scene-id', help='Scene ID for regenerate'),
    model: str = typer.Option(None, '--model', help='Model to use for generation'),
    job_id: str = typer.Option(None, '--job-id', help='Job ID for status/cancel'),
    status: str = typer.Option(None, '--status', help='Filter jobs by status'),
    limit: int = typer.Option(None, '--limit', help='Max jobs to return'),
    cadre_index: str = typer.Option(None, '--cadre-index', help='Scene index (for preview/verify)'),
    all_remaining: str = typer.Option(None, '--all-remaining', help="Set to 'true' to preview all remaining scenes (for preview)"),
    analysis_ids: str = typer.Option(None, '--analysis-ids', help='Comma-separated analysis UUIDs (for generate)'),
    topic: str = typer.Option(None, '--topic', help='Video topic (for generate)'),
    style: str = typer.Option(None, '--style', help='Visual style (for generate)'),
    expected_revision: str = typer.Option(None, '--expected-revision', help='Project revision for optimistic locking (for regenerate)'),
):
    'Generate videos, preview storyboards, verify quality, and manage rendering jobs. Use video_project for project creation and editing.'
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: video_generate
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'video_generate'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'job_list', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
