# Auto-generated by scripts/build_tool_artifacts.py — do not edit manually
# Registration: from .commands._generated import workspace as gen_workspace
# Registration: app.add_typer(gen_workspace.app, name='workspace')
import time

import typer

from ..api import api_request, handle_errors, log_action_to_session, make_client
from ..config import load_config
from ..output import emit, emit_error
from ..session import get_active_session

app = typer.Typer(help="Workspace and batch operations. Actions: 'query' (default): query collection by name. 'filter': filter collection items. 'get_items': get item details. 'delete': delete a collection. 'batch_analyze': analyze all videos in a collection. 'cancel_batch'/'retry_batch'/'batch_status': manage batch jobs.", no_args_is_help=True)


def _require_config():
    config = load_config()
    if not config:
        emit_error("not_authenticated", "No API key configured. Run: freddy auth login --api-key <key>")
    return config


def _maybe_log_action(client, tool_name: str, input_data: dict, result: dict, duration_ms: int) -> None:
    """Log action if session is active. Non-fatal."""
    session = get_active_session()
    if session:
        output_summary = {"status": "ok"}
        if "data" in result:
            output_summary["count"] = len(result["data"]) if isinstance(result["data"], list) else 1
        log_action_to_session(
            client, session.session_id, tool_name,
            input_summary=input_data, output_summary=output_summary, duration_ms=duration_ms,
        )


@app.command('query')
@handle_errors
def query(
    collection_name: str = typer.Option(None, '--collection-name', help='Name of the workspace collection'),
    collection_id: str = typer.Option(None, '--collection-id', help='UUID of the workspace collection (for batch_analyze)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (default: engagement_rate)'),
    min_views: int = typer.Option(None, '--min-views', help='Minimum view count filter'),
    max_views: int = typer.Option(None, '--max-views', help='Maximum views filter'),
    min_engagement: float = typer.Option(None, '--min-engagement', help='Minimum engagement rate filter (0.0-1.0)'),
    platform: str = typer.Option(None, '--platform', help='Platform filter'),
    limit: int = typer.Option(None, '--limit', help='Max items to return (1-50, default 10)'),
    item_ids: str = typer.Option(None, '--item-ids', help='Comma-separated workspace item UUIDs for detail view'),
    top_n: int = typer.Option(None, '--top-n', help='Get top N items with full detail'),
    analysis_types: str = typer.Option(None, '--analysis-types', help='Types of analysis for batch_analyze (default: brand_safety)'),
    batch_id: str = typer.Option(None, '--batch-id', help='Batch UUID (for cancel_batch/retry_batch/batch_status)'),
    group_by: str = typer.Option(None, '--group-by', help='Group results by field (for browse_library)'),
    job_id: str = typer.Option(None, '--job-id', help='Generation job UUID (for cancel_generation_job)'),
):
    "Workspace and batch operations. Actions: 'query' (default): query collection by name. 'filter': filter collection items. 'get_items': get item details. 'delete': delete a collection. 'batch_analyze': analyze all videos in a collection. 'cancel_batch'/'retry_batch'/'batch_status': manage batch jobs."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: workspace
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'workspace'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'query', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('filter')
@handle_errors
def filter(
    collection_name: str = typer.Option(None, '--collection-name', help='Name of the workspace collection'),
    collection_id: str = typer.Option(None, '--collection-id', help='UUID of the workspace collection (for batch_analyze)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (default: engagement_rate)'),
    min_views: int = typer.Option(None, '--min-views', help='Minimum view count filter'),
    max_views: int = typer.Option(None, '--max-views', help='Maximum views filter'),
    min_engagement: float = typer.Option(None, '--min-engagement', help='Minimum engagement rate filter (0.0-1.0)'),
    platform: str = typer.Option(None, '--platform', help='Platform filter'),
    limit: int = typer.Option(None, '--limit', help='Max items to return (1-50, default 10)'),
    item_ids: str = typer.Option(None, '--item-ids', help='Comma-separated workspace item UUIDs for detail view'),
    top_n: int = typer.Option(None, '--top-n', help='Get top N items with full detail'),
    analysis_types: str = typer.Option(None, '--analysis-types', help='Types of analysis for batch_analyze (default: brand_safety)'),
    batch_id: str = typer.Option(None, '--batch-id', help='Batch UUID (for cancel_batch/retry_batch/batch_status)'),
    group_by: str = typer.Option(None, '--group-by', help='Group results by field (for browse_library)'),
    job_id: str = typer.Option(None, '--job-id', help='Generation job UUID (for cancel_generation_job)'),
):
    "Workspace and batch operations. Actions: 'query' (default): query collection by name. 'filter': filter collection items. 'get_items': get item details. 'delete': delete a collection. 'batch_analyze': analyze all videos in a collection. 'cancel_batch'/'retry_batch'/'batch_status': manage batch jobs."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: workspace
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'workspace'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'filter', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('get-items')
@handle_errors
def get_items(
    collection_name: str = typer.Option(None, '--collection-name', help='Name of the workspace collection'),
    collection_id: str = typer.Option(None, '--collection-id', help='UUID of the workspace collection (for batch_analyze)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (default: engagement_rate)'),
    min_views: int = typer.Option(None, '--min-views', help='Minimum view count filter'),
    max_views: int = typer.Option(None, '--max-views', help='Maximum views filter'),
    min_engagement: float = typer.Option(None, '--min-engagement', help='Minimum engagement rate filter (0.0-1.0)'),
    platform: str = typer.Option(None, '--platform', help='Platform filter'),
    limit: int = typer.Option(None, '--limit', help='Max items to return (1-50, default 10)'),
    item_ids: str = typer.Option(None, '--item-ids', help='Comma-separated workspace item UUIDs for detail view'),
    top_n: int = typer.Option(None, '--top-n', help='Get top N items with full detail'),
    analysis_types: str = typer.Option(None, '--analysis-types', help='Types of analysis for batch_analyze (default: brand_safety)'),
    batch_id: str = typer.Option(None, '--batch-id', help='Batch UUID (for cancel_batch/retry_batch/batch_status)'),
    group_by: str = typer.Option(None, '--group-by', help='Group results by field (for browse_library)'),
    job_id: str = typer.Option(None, '--job-id', help='Generation job UUID (for cancel_generation_job)'),
):
    "Workspace and batch operations. Actions: 'query' (default): query collection by name. 'filter': filter collection items. 'get_items': get item details. 'delete': delete a collection. 'batch_analyze': analyze all videos in a collection. 'cancel_batch'/'retry_batch'/'batch_status': manage batch jobs."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: workspace
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'workspace'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'get_items', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('delete')
@handle_errors
def delete(
    collection_name: str = typer.Option(None, '--collection-name', help='Name of the workspace collection'),
    collection_id: str = typer.Option(None, '--collection-id', help='UUID of the workspace collection (for batch_analyze)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (default: engagement_rate)'),
    min_views: int = typer.Option(None, '--min-views', help='Minimum view count filter'),
    max_views: int = typer.Option(None, '--max-views', help='Maximum views filter'),
    min_engagement: float = typer.Option(None, '--min-engagement', help='Minimum engagement rate filter (0.0-1.0)'),
    platform: str = typer.Option(None, '--platform', help='Platform filter'),
    limit: int = typer.Option(None, '--limit', help='Max items to return (1-50, default 10)'),
    item_ids: str = typer.Option(None, '--item-ids', help='Comma-separated workspace item UUIDs for detail view'),
    top_n: int = typer.Option(None, '--top-n', help='Get top N items with full detail'),
    analysis_types: str = typer.Option(None, '--analysis-types', help='Types of analysis for batch_analyze (default: brand_safety)'),
    batch_id: str = typer.Option(None, '--batch-id', help='Batch UUID (for cancel_batch/retry_batch/batch_status)'),
    group_by: str = typer.Option(None, '--group-by', help='Group results by field (for browse_library)'),
    job_id: str = typer.Option(None, '--job-id', help='Generation job UUID (for cancel_generation_job)'),
):
    "Workspace and batch operations. Actions: 'query' (default): query collection by name. 'filter': filter collection items. 'get_items': get item details. 'delete': delete a collection. 'batch_analyze': analyze all videos in a collection. 'cancel_batch'/'retry_batch'/'batch_status': manage batch jobs."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: workspace
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'workspace'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'delete', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('batch-analyze')
@handle_errors
def batch_analyze(
    collection_name: str = typer.Option(None, '--collection-name', help='Name of the workspace collection'),
    collection_id: str = typer.Option(None, '--collection-id', help='UUID of the workspace collection (for batch_analyze)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (default: engagement_rate)'),
    min_views: int = typer.Option(None, '--min-views', help='Minimum view count filter'),
    max_views: int = typer.Option(None, '--max-views', help='Maximum views filter'),
    min_engagement: float = typer.Option(None, '--min-engagement', help='Minimum engagement rate filter (0.0-1.0)'),
    platform: str = typer.Option(None, '--platform', help='Platform filter'),
    limit: int = typer.Option(None, '--limit', help='Max items to return (1-50, default 10)'),
    item_ids: str = typer.Option(None, '--item-ids', help='Comma-separated workspace item UUIDs for detail view'),
    top_n: int = typer.Option(None, '--top-n', help='Get top N items with full detail'),
    analysis_types: str = typer.Option(None, '--analysis-types', help='Types of analysis for batch_analyze (default: brand_safety)'),
    batch_id: str = typer.Option(None, '--batch-id', help='Batch UUID (for cancel_batch/retry_batch/batch_status)'),
    group_by: str = typer.Option(None, '--group-by', help='Group results by field (for browse_library)'),
    job_id: str = typer.Option(None, '--job-id', help='Generation job UUID (for cancel_generation_job)'),
):
    "Workspace and batch operations. Actions: 'query' (default): query collection by name. 'filter': filter collection items. 'get_items': get item details. 'delete': delete a collection. 'batch_analyze': analyze all videos in a collection. 'cancel_batch'/'retry_batch'/'batch_status': manage batch jobs."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: workspace
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'workspace'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'batch_analyze', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('cancel-batch')
@handle_errors
def cancel_batch(
    collection_name: str = typer.Option(None, '--collection-name', help='Name of the workspace collection'),
    collection_id: str = typer.Option(None, '--collection-id', help='UUID of the workspace collection (for batch_analyze)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (default: engagement_rate)'),
    min_views: int = typer.Option(None, '--min-views', help='Minimum view count filter'),
    max_views: int = typer.Option(None, '--max-views', help='Maximum views filter'),
    min_engagement: float = typer.Option(None, '--min-engagement', help='Minimum engagement rate filter (0.0-1.0)'),
    platform: str = typer.Option(None, '--platform', help='Platform filter'),
    limit: int = typer.Option(None, '--limit', help='Max items to return (1-50, default 10)'),
    item_ids: str = typer.Option(None, '--item-ids', help='Comma-separated workspace item UUIDs for detail view'),
    top_n: int = typer.Option(None, '--top-n', help='Get top N items with full detail'),
    analysis_types: str = typer.Option(None, '--analysis-types', help='Types of analysis for batch_analyze (default: brand_safety)'),
    batch_id: str = typer.Option(None, '--batch-id', help='Batch UUID (for cancel_batch/retry_batch/batch_status)'),
    group_by: str = typer.Option(None, '--group-by', help='Group results by field (for browse_library)'),
    job_id: str = typer.Option(None, '--job-id', help='Generation job UUID (for cancel_generation_job)'),
):
    "Workspace and batch operations. Actions: 'query' (default): query collection by name. 'filter': filter collection items. 'get_items': get item details. 'delete': delete a collection. 'batch_analyze': analyze all videos in a collection. 'cancel_batch'/'retry_batch'/'batch_status': manage batch jobs."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: workspace
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'workspace'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'cancel_batch', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('retry-batch')
@handle_errors
def retry_batch(
    collection_name: str = typer.Option(None, '--collection-name', help='Name of the workspace collection'),
    collection_id: str = typer.Option(None, '--collection-id', help='UUID of the workspace collection (for batch_analyze)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (default: engagement_rate)'),
    min_views: int = typer.Option(None, '--min-views', help='Minimum view count filter'),
    max_views: int = typer.Option(None, '--max-views', help='Maximum views filter'),
    min_engagement: float = typer.Option(None, '--min-engagement', help='Minimum engagement rate filter (0.0-1.0)'),
    platform: str = typer.Option(None, '--platform', help='Platform filter'),
    limit: int = typer.Option(None, '--limit', help='Max items to return (1-50, default 10)'),
    item_ids: str = typer.Option(None, '--item-ids', help='Comma-separated workspace item UUIDs for detail view'),
    top_n: int = typer.Option(None, '--top-n', help='Get top N items with full detail'),
    analysis_types: str = typer.Option(None, '--analysis-types', help='Types of analysis for batch_analyze (default: brand_safety)'),
    batch_id: str = typer.Option(None, '--batch-id', help='Batch UUID (for cancel_batch/retry_batch/batch_status)'),
    group_by: str = typer.Option(None, '--group-by', help='Group results by field (for browse_library)'),
    job_id: str = typer.Option(None, '--job-id', help='Generation job UUID (for cancel_generation_job)'),
):
    "Workspace and batch operations. Actions: 'query' (default): query collection by name. 'filter': filter collection items. 'get_items': get item details. 'delete': delete a collection. 'batch_analyze': analyze all videos in a collection. 'cancel_batch'/'retry_batch'/'batch_status': manage batch jobs."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: workspace
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'workspace'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'retry_batch', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('batch-status')
@handle_errors
def batch_status(
    collection_name: str = typer.Option(None, '--collection-name', help='Name of the workspace collection'),
    collection_id: str = typer.Option(None, '--collection-id', help='UUID of the workspace collection (for batch_analyze)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (default: engagement_rate)'),
    min_views: int = typer.Option(None, '--min-views', help='Minimum view count filter'),
    max_views: int = typer.Option(None, '--max-views', help='Maximum views filter'),
    min_engagement: float = typer.Option(None, '--min-engagement', help='Minimum engagement rate filter (0.0-1.0)'),
    platform: str = typer.Option(None, '--platform', help='Platform filter'),
    limit: int = typer.Option(None, '--limit', help='Max items to return (1-50, default 10)'),
    item_ids: str = typer.Option(None, '--item-ids', help='Comma-separated workspace item UUIDs for detail view'),
    top_n: int = typer.Option(None, '--top-n', help='Get top N items with full detail'),
    analysis_types: str = typer.Option(None, '--analysis-types', help='Types of analysis for batch_analyze (default: brand_safety)'),
    batch_id: str = typer.Option(None, '--batch-id', help='Batch UUID (for cancel_batch/retry_batch/batch_status)'),
    group_by: str = typer.Option(None, '--group-by', help='Group results by field (for browse_library)'),
    job_id: str = typer.Option(None, '--job-id', help='Generation job UUID (for cancel_generation_job)'),
):
    "Workspace and batch operations. Actions: 'query' (default): query collection by name. 'filter': filter collection items. 'get_items': get item details. 'delete': delete a collection. 'batch_analyze': analyze all videos in a collection. 'cancel_batch'/'retry_batch'/'batch_status': manage batch jobs."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: workspace
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'workspace'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'batch_status', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('browse-library')
@handle_errors
def browse_library(
    collection_name: str = typer.Option(None, '--collection-name', help='Name of the workspace collection'),
    collection_id: str = typer.Option(None, '--collection-id', help='UUID of the workspace collection (for batch_analyze)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (default: engagement_rate)'),
    min_views: int = typer.Option(None, '--min-views', help='Minimum view count filter'),
    max_views: int = typer.Option(None, '--max-views', help='Maximum views filter'),
    min_engagement: float = typer.Option(None, '--min-engagement', help='Minimum engagement rate filter (0.0-1.0)'),
    platform: str = typer.Option(None, '--platform', help='Platform filter'),
    limit: int = typer.Option(None, '--limit', help='Max items to return (1-50, default 10)'),
    item_ids: str = typer.Option(None, '--item-ids', help='Comma-separated workspace item UUIDs for detail view'),
    top_n: int = typer.Option(None, '--top-n', help='Get top N items with full detail'),
    analysis_types: str = typer.Option(None, '--analysis-types', help='Types of analysis for batch_analyze (default: brand_safety)'),
    batch_id: str = typer.Option(None, '--batch-id', help='Batch UUID (for cancel_batch/retry_batch/batch_status)'),
    group_by: str = typer.Option(None, '--group-by', help='Group results by field (for browse_library)'),
    job_id: str = typer.Option(None, '--job-id', help='Generation job UUID (for cancel_generation_job)'),
):
    "Workspace and batch operations. Actions: 'query' (default): query collection by name. 'filter': filter collection items. 'get_items': get item details. 'delete': delete a collection. 'batch_analyze': analyze all videos in a collection. 'cancel_batch'/'retry_batch'/'batch_status': manage batch jobs."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: workspace
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'workspace'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'browse_library', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('cancel-generation-job')
@handle_errors
def cancel_generation_job(
    collection_name: str = typer.Option(None, '--collection-name', help='Name of the workspace collection'),
    collection_id: str = typer.Option(None, '--collection-id', help='UUID of the workspace collection (for batch_analyze)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (default: engagement_rate)'),
    min_views: int = typer.Option(None, '--min-views', help='Minimum view count filter'),
    max_views: int = typer.Option(None, '--max-views', help='Maximum views filter'),
    min_engagement: float = typer.Option(None, '--min-engagement', help='Minimum engagement rate filter (0.0-1.0)'),
    platform: str = typer.Option(None, '--platform', help='Platform filter'),
    limit: int = typer.Option(None, '--limit', help='Max items to return (1-50, default 10)'),
    item_ids: str = typer.Option(None, '--item-ids', help='Comma-separated workspace item UUIDs for detail view'),
    top_n: int = typer.Option(None, '--top-n', help='Get top N items with full detail'),
    analysis_types: str = typer.Option(None, '--analysis-types', help='Types of analysis for batch_analyze (default: brand_safety)'),
    batch_id: str = typer.Option(None, '--batch-id', help='Batch UUID (for cancel_batch/retry_batch/batch_status)'),
    group_by: str = typer.Option(None, '--group-by', help='Group results by field (for browse_library)'),
    job_id: str = typer.Option(None, '--job-id', help='Generation job UUID (for cancel_generation_job)'),
):
    "Workspace and batch operations. Actions: 'query' (default): query collection by name. 'filter': filter collection items. 'get_items': get item details. 'delete': delete a collection. 'batch_analyze': analyze all videos in a collection. 'cancel_batch'/'retry_batch'/'batch_status': manage batch jobs."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: workspace
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'workspace'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'cancel_generation_job', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)


@app.command('get-item-scores')
@handle_errors
def get_item_scores(
    collection_name: str = typer.Option(None, '--collection-name', help='Name of the workspace collection'),
    collection_id: str = typer.Option(None, '--collection-id', help='UUID of the workspace collection (for batch_analyze)'),
    sort_by: str = typer.Option(None, '--sort-by', help='Sort field (default: engagement_rate)'),
    min_views: int = typer.Option(None, '--min-views', help='Minimum view count filter'),
    max_views: int = typer.Option(None, '--max-views', help='Maximum views filter'),
    min_engagement: float = typer.Option(None, '--min-engagement', help='Minimum engagement rate filter (0.0-1.0)'),
    platform: str = typer.Option(None, '--platform', help='Platform filter'),
    limit: int = typer.Option(None, '--limit', help='Max items to return (1-50, default 10)'),
    item_ids: str = typer.Option(None, '--item-ids', help='Comma-separated workspace item UUIDs for detail view'),
    top_n: int = typer.Option(None, '--top-n', help='Get top N items with full detail'),
    analysis_types: str = typer.Option(None, '--analysis-types', help='Types of analysis for batch_analyze (default: brand_safety)'),
    batch_id: str = typer.Option(None, '--batch-id', help='Batch UUID (for cancel_batch/retry_batch/batch_status)'),
    group_by: str = typer.Option(None, '--group-by', help='Group results by field (for browse_library)'),
    job_id: str = typer.Option(None, '--job-id', help='Generation job UUID (for cancel_generation_job)'),
):
    "Workspace and batch operations. Actions: 'query' (default): query collection by name. 'filter': filter collection items. 'get_items': get item details. 'delete': delete a collection. 'batch_analyze': analyze all videos in a collection. 'cancel_batch'/'retry_batch'/'batch_status': manage batch jobs."
    config = _require_config()
    client = make_client(config)

    start_time = time.monotonic()
    # TODO: Wire to REST endpoint. Tool: workspace
    result = api_request(client, "POST", "/v1/agent/chat", json_data={"message": "...", "tool_hint": 'workspace'})
    duration_ms = int((time.monotonic() - start_time) * 1000)

    _maybe_log_action(client, 'get_item_scores', {}, result, duration_ms)

    from ..main import get_state
    emit(result, human=get_state().human)
