"""Tests for harness.safety — main-repo leak detection only.

Per-track SCOPE_ALLOWLIST + check_scope were removed — the fixer prompt
now describes each track's surface in prose, and per-worker isolation
replaces the regex containment. What remains is `check_no_leak`, which
catches cases where a fixer writes absolute paths OUTSIDE its worktree
back into the parent repo.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

from harness.safety import check_no_leak, snapshot_dirty


def _init_repo(tmp_path: Path) -> Path:
    subprocess.run(["git", "init", "-q", "-b", "main", str(tmp_path)], check=True)
    subprocess.run(["git", "-C", str(tmp_path), "config", "user.email", "t@test"], check=True)
    subprocess.run(["git", "-C", str(tmp_path), "config", "user.name", "t"], check=True)
    (tmp_path / "seed.txt").write_text("seed\n", encoding="utf-8")
    subprocess.run(["git", "-C", str(tmp_path), "add", "."], check=True)
    subprocess.run(["git", "-C", str(tmp_path), "commit", "-qm", "seed"], check=True)
    return tmp_path


def _init_repo_with_tracked_dirs(tmp_path: Path) -> Path:
    """Repo with cli/freddy/ and docs/plans/ already tracked so new files in them
    show as specific paths in `git status --porcelain`, not as top-level `??` dirs."""
    repo = tmp_path
    subprocess.run(["git", "init", "-q", "-b", "main", str(repo)], check=True)
    subprocess.run(["git", "-C", str(repo), "config", "user.email", "t@test"], check=True)
    subprocess.run(["git", "-C", str(repo), "config", "user.name", "t"], check=True)
    (repo / "cli" / "freddy").mkdir(parents=True)
    (repo / "cli" / "freddy" / "keep.py").write_text("keep\n", encoding="utf-8")
    (repo / "docs" / "plans").mkdir(parents=True)
    (repo / "docs" / "plans" / "keep.md").write_text("keep\n", encoding="utf-8")
    subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
    subprocess.run(["git", "-C", str(repo), "commit", "-qm", "seed"], check=True)
    return repo


def test_check_no_leak_clean_main_repo(tmp_path):
    repo = _init_repo(tmp_path)
    snapshot = snapshot_dirty(repo)
    actionable, advisory = check_no_leak(snapshot, main_repo=repo)
    assert actionable == []
    assert advisory == []


def test_check_no_leak_detects_new_dirty_in_fixer_reachable_path(tmp_path):
    """Reachable dirty paths (cli/, src/, autoresearch/, frontend/, tests/,
    pyproject.toml) go into `actionable` — rollback-eligible because plausibly
    fixer-caused via an absolute-path write outside the worktree."""
    repo = _init_repo_with_tracked_dirs(tmp_path)
    snapshot = snapshot_dirty(repo)
    (repo / "cli" / "freddy" / "leaked.py").write_text("leak\n", encoding="utf-8")
    actionable, advisory = check_no_leak(snapshot, main_repo=repo)
    assert actionable == ["cli/freddy/leaked.py"]
    assert advisory == []


def test_check_no_leak_routes_docs_to_advisory(tmp_path):
    """docs/plans/* is operator dev activity — advisory only, never rollback.
    Smoke run 20260422-224908 rolled back 5 findings because a parallel
    Claude session was editing docs/plans/*; that must not happen."""
    repo = _init_repo_with_tracked_dirs(tmp_path)
    snapshot = snapshot_dirty(repo)
    (repo / "docs" / "plans" / "new-plan.md").write_text("plan\n", encoding="utf-8")
    actionable, advisory = check_no_leak(snapshot, main_repo=repo)
    assert actionable == []
    assert advisory == ["docs/plans/new-plan.md"]


def test_check_no_leak_tests_now_reachable(tmp_path):
    """tests/ is now in `_FIXER_REACHABLE` because the fixer prompt permits
    tests/** edits when they are a direct consequence of a code fix — so
    main-repo writes to tests/ are plausibly fixer-caused and must trigger
    rollback + cleanup, not just advisory logging."""
    repo = _init_repo_with_tracked_dirs(tmp_path)
    (repo / "tests").mkdir(parents=True)
    (repo / "tests" / "keep.py").write_text("keep\n", encoding="utf-8")
    subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
    subprocess.run(["git", "-C", str(repo), "commit", "-qm", "seed tests"], check=True)
    snapshot = snapshot_dirty(repo)
    (repo / "tests" / "leaked.py").write_text("leak\n", encoding="utf-8")
    actionable, advisory = check_no_leak(snapshot, main_repo=repo)
    assert actionable == ["tests/leaked.py"]
    assert advisory == []


def test_check_no_leak_still_ignores_harness_artifacts(tmp_path):
    """HARNESS_ARTIFACTS paths (backend.log, sessions/, harness/blocked-*.md)
    are generated by the harness itself and must not count as leaks in either
    category."""
    repo = _init_repo_with_tracked_dirs(tmp_path)
    snapshot = snapshot_dirty(repo)
    (repo / "backend.log").write_text("log\n", encoding="utf-8")
    (repo / "sessions").mkdir(parents=True)
    (repo / "sessions" / "x.json").write_text("{}\n", encoding="utf-8")
    actionable, advisory = check_no_leak(snapshot, main_repo=repo)
    assert actionable == []
    assert advisory == []


def test_check_no_leak_ignores_preexisting_dirty(tmp_path):
    repo = _init_repo(tmp_path)
    (repo / "already.txt").write_text("a\n", encoding="utf-8")
    snapshot = snapshot_dirty(repo)
    assert "already.txt" in snapshot
    actionable, advisory = check_no_leak(snapshot, main_repo=repo)
    assert actionable == []
    assert advisory == []
