"""Tests for harness.safety — scope allowlist + leak detection."""
from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from harness.safety import SCOPE_ALLOWLIST, check_no_leak, check_scope, snapshot_dirty


def _init_repo(tmp_path: Path) -> Path:
    subprocess.run(["git", "init", "-q", "-b", "main", str(tmp_path)], check=True)
    subprocess.run(["git", "-C", str(tmp_path), "config", "user.email", "t@test"], check=True)
    subprocess.run(["git", "-C", str(tmp_path), "config", "user.name", "t"], check=True)
    (tmp_path / "seed.txt").write_text("seed\n", encoding="utf-8")
    subprocess.run(["git", "-C", str(tmp_path), "add", "."], check=True)
    subprocess.run(["git", "-C", str(tmp_path), "commit", "-qm", "seed"], check=True)
    return tmp_path


def _write_uncommitted(repo: Path, rel: str, body: str = "x") -> None:
    """Write a file in the worktree but DO NOT commit — mirrors fixer behavior."""
    target = repo / rel
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8")


def _pre_head(repo: Path) -> str:
    return subprocess.check_output(["git", "-C", str(repo), "rev-parse", "HEAD"], text=True).strip()


@pytest.mark.parametrize("track,path", [
    ("a", "cli/freddy/commands/client.py"),
    ("a", "pyproject.toml"),
    ("b", "src/api/main.py"),
    ("b", "autoresearch/evolve.py"),
    ("c", "frontend/package.json"),
    ("c", "frontend/vite.config.ts"),
])
def test_check_scope_allows_matching_paths(tmp_path, track, path):
    repo = _init_repo(tmp_path)
    pre = _pre_head(repo)
    _write_uncommitted(repo, path)
    assert check_scope(repo, pre, track) is None


@pytest.mark.parametrize("track,path", [
    ("a", "tests/harness/test_run.py"),
    ("a", "harness/safety.py"),
    ("a", "src/api/main.py"),
    ("b", "cli/freddy/main.py"),
    ("b", "tests/unit/test_x.py"),
    ("c", "src/api/main.py"),
])
def test_check_scope_flags_forbidden_paths(tmp_path, track, path):
    repo = _init_repo(tmp_path)
    pre = _pre_head(repo)
    _write_uncommitted(repo, path)
    violations = check_scope(repo, pre, track)
    assert violations == [path]


def test_check_scope_returns_only_violations(tmp_path):
    repo = _init_repo(tmp_path)
    pre = _pre_head(repo)
    _write_uncommitted(repo, "cli/freddy/x.py")
    _write_uncommitted(repo, "harness/forbidden.py")
    violations = check_scope(repo, pre, "a")
    assert violations == ["harness/forbidden.py"]


def test_check_scope_ignores_harness_artifacts(tmp_path):
    # backend.log is generated by worktree.restart_backend; never a fixer edit.
    repo = _init_repo(tmp_path)
    pre = _pre_head(repo)
    _write_uncommitted(repo, "backend.log", "log output\n")
    _write_uncommitted(repo, "cli/freddy/ok.py", "pass\n")
    assert check_scope(repo, pre, "a") is None


def test_check_no_leak_clean_main_repo(tmp_path):
    repo = _init_repo(tmp_path)
    snapshot = snapshot_dirty(repo)
    assert check_no_leak(snapshot, main_repo=repo) is None


def _init_repo_with_tracked_dirs(tmp_path: Path) -> Path:
    """Repo with cli/freddy/ and docs/plans/ already tracked so new files in them
    show as specific paths in `git status --porcelain`, not as top-level `??` dirs."""
    repo = tmp_path
    subprocess.run(["git", "init", "-q", "-b", "main", str(repo)], check=True)
    subprocess.run(["git", "-C", str(repo), "config", "user.email", "t@test"], check=True)
    subprocess.run(["git", "-C", str(repo), "config", "user.name", "t"], check=True)
    (repo / "cli" / "freddy").mkdir(parents=True)
    (repo / "cli" / "freddy" / "keep.py").write_text("keep\n", encoding="utf-8")
    (repo / "docs" / "plans").mkdir(parents=True)
    (repo / "docs" / "plans" / "keep.md").write_text("keep\n", encoding="utf-8")
    subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
    subprocess.run(["git", "-C", str(repo), "commit", "-qm", "seed"], check=True)
    return repo


def test_check_no_leak_detects_new_dirty_in_fixer_reachable_path(tmp_path):
    repo = _init_repo_with_tracked_dirs(tmp_path)
    snapshot = snapshot_dirty(repo)
    (repo / "cli" / "freddy" / "leaked.py").write_text("leak\n", encoding="utf-8")
    leaks = check_no_leak(snapshot, main_repo=repo)
    assert leaks == ["cli/freddy/leaked.py"]


def test_check_no_leak_ignores_new_dirty_outside_fixer_reach(tmp_path):
    # docs/plans is outside every track's scope — concurrent dev activity
    # on those paths is not a fixer leak.
    repo = _init_repo_with_tracked_dirs(tmp_path)
    snapshot = snapshot_dirty(repo)
    (repo / "docs" / "plans" / "new-plan.md").write_text("plan\n", encoding="utf-8")
    assert check_no_leak(snapshot, main_repo=repo) is None


def test_check_no_leak_ignores_preexisting_dirty(tmp_path):
    repo = _init_repo(tmp_path)
    (repo / "already.txt").write_text("a\n", encoding="utf-8")
    snapshot = snapshot_dirty(repo)
    assert "already.txt" in snapshot
    assert check_no_leak(snapshot, main_repo=repo) is None


def test_scope_allowlist_has_three_tracks():
    assert set(SCOPE_ALLOWLIST) == {"a", "b", "c"}
