"""Tests for harness.safety — scope allowlist + leak detection."""
from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from harness.safety import SCOPE_ALLOWLIST, check_no_leak, check_scope, snapshot_dirty


def _init_repo(tmp_path: Path) -> Path:
    subprocess.run(["git", "init", "-q", "-b", "main", str(tmp_path)], check=True)
    subprocess.run(["git", "-C", str(tmp_path), "config", "user.email", "t@test"], check=True)
    subprocess.run(["git", "-C", str(tmp_path), "config", "user.name", "t"], check=True)
    (tmp_path / "seed.txt").write_text("seed\n", encoding="utf-8")
    subprocess.run(["git", "-C", str(tmp_path), "add", "."], check=True)
    subprocess.run(["git", "-C", str(tmp_path), "commit", "-qm", "seed"], check=True)
    return tmp_path


def _write_uncommitted(repo: Path, rel: str, body: str = "x") -> None:
    """Write a file in the worktree but DO NOT commit — mirrors fixer behavior."""
    target = repo / rel
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8")


def _pre_head(repo: Path) -> str:
    return subprocess.check_output(["git", "-C", str(repo), "rev-parse", "HEAD"], text=True).strip()


@pytest.mark.parametrize("track,path", [
    ("a", "cli/freddy/commands/client.py"),
    ("a", "pyproject.toml"),
    ("b", "src/api/main.py"),
    ("b", "autoresearch/evolve.py"),
    ("c", "frontend/package.json"),
    ("c", "frontend/vite.config.ts"),
])
def test_check_scope_allows_matching_paths(tmp_path, track, path):
    repo = _init_repo(tmp_path)
    pre = _pre_head(repo)
    _write_uncommitted(repo, path)
    assert check_scope(repo, pre, track) is None


@pytest.mark.parametrize("track,path", [
    ("a", "tests/harness/test_run.py"),
    ("a", "harness/safety.py"),
    ("a", "docs/plans/new.md"),
    ("b", "tests/unit/test_x.py"),
    ("b", "harness/run.py"),
    ("c", "harness/engine.py"),
])
def test_check_scope_flags_paths_outside_all_allowlists(tmp_path, track, path):
    """Paths matching NO track's allowlist are always violations for any track."""
    repo = _init_repo(tmp_path)
    pre = _pre_head(repo)
    _write_uncommitted(repo, path)
    violations = check_scope(repo, pre, track)
    assert violations == [path]


@pytest.mark.parametrize("track,peer_path", [
    ("a", "src/api/main.py"),        # peer B's scope
    ("a", "frontend/vite.config.ts"),  # peer C's scope
    ("b", "cli/freddy/main.py"),     # peer A's scope
    ("b", "frontend/package.json"),  # peer C's scope
    ("c", "autoresearch/evolve.py"),  # peer B's scope
    ("c", "cli/freddy/x.py"),        # peer A's scope
])
def test_check_scope_ignores_peer_tracks_dirty_files(tmp_path, track, peer_path):
    """Parallel execution: files matching another track's allowlist are peer work.

    This track's check_scope must skip them — they'll be validated by their own
    track's check_scope run.
    """
    repo = _init_repo(tmp_path)
    pre = _pre_head(repo)
    _write_uncommitted(repo, peer_path)
    assert check_scope(repo, pre, track) is None


def test_check_scope_returns_only_violations(tmp_path):
    repo = _init_repo(tmp_path)
    pre = _pre_head(repo)
    _write_uncommitted(repo, "cli/freddy/x.py")
    _write_uncommitted(repo, "harness/forbidden.py")
    violations = check_scope(repo, pre, "a")
    assert violations == ["harness/forbidden.py"]


def test_check_scope_parallel_scenario_a_only_flags_own_violations(tmp_path):
    """Track A has: one in-scope edit, one peer-attributable edit (src/), one true violation.
    check_scope should return only the true violation."""
    repo = _init_repo(tmp_path)
    pre = _pre_head(repo)
    _write_uncommitted(repo, "cli/freddy/mine.py")         # in A's scope
    _write_uncommitted(repo, "src/api/main.py")            # B's scope — ignored
    _write_uncommitted(repo, "harness/out_of_scope.py")    # no track — flagged
    violations = check_scope(repo, pre, "a")
    assert violations == ["harness/out_of_scope.py"]


def test_check_scope_ignores_harness_artifacts(tmp_path):
    # backend.log is generated by worktree.restart_backend; never a fixer edit.
    repo = _init_repo(tmp_path)
    pre = _pre_head(repo)
    _write_uncommitted(repo, "backend.log", "log output\n")
    _write_uncommitted(repo, "cli/freddy/ok.py", "pass\n")
    assert check_scope(repo, pre, "a") is None


@pytest.mark.parametrize("artifact", [
    "harness/blocked-F-a-1-1.md",           # fixer's "I can't fix this" signal
    "harness/blocked-F-c-2-3.md",
    "sessions/competitive/test-client/foo.json",  # freddy CLI session write
    "sessions/monitor/bar.json",
])
def test_check_scope_ignores_fixer_side_effect_artifacts(tmp_path, artifact):
    """harness/blocked-*.md (written by fixer prompt when blocked) and sessions/*
    (written as a side effect of fixer/verifier running freddy CLI repro commands)
    are not fixer edits and must not count as scope violations."""
    repo = _init_repo(tmp_path)
    pre = _pre_head(repo)
    _write_uncommitted(repo, artifact, "data\n")
    _write_uncommitted(repo, "cli/freddy/ok.py", "pass\n")
    assert check_scope(repo, pre, "a") is None


def test_check_scope_still_flags_non_blocked_harness_files(tmp_path):
    """Only `harness/blocked-*.md` is exempted — other harness/ writes are still violations."""
    repo = _init_repo(tmp_path)
    pre = _pre_head(repo)
    _write_uncommitted(repo, "harness/engine.py", "tampered\n")
    violations = check_scope(repo, pre, "a")
    assert violations == ["harness/engine.py"]


def test_check_no_leak_clean_main_repo(tmp_path):
    repo = _init_repo(tmp_path)
    snapshot = snapshot_dirty(repo)
    actionable, advisory = check_no_leak(snapshot, main_repo=repo)
    assert actionable == []
    assert advisory == []


def _init_repo_with_tracked_dirs(tmp_path: Path) -> Path:
    """Repo with cli/freddy/ and docs/plans/ already tracked so new files in them
    show as specific paths in `git status --porcelain`, not as top-level `??` dirs."""
    repo = tmp_path
    subprocess.run(["git", "init", "-q", "-b", "main", str(repo)], check=True)
    subprocess.run(["git", "-C", str(repo), "config", "user.email", "t@test"], check=True)
    subprocess.run(["git", "-C", str(repo), "config", "user.name", "t"], check=True)
    (repo / "cli" / "freddy").mkdir(parents=True)
    (repo / "cli" / "freddy" / "keep.py").write_text("keep\n", encoding="utf-8")
    (repo / "docs" / "plans").mkdir(parents=True)
    (repo / "docs" / "plans" / "keep.md").write_text("keep\n", encoding="utf-8")
    subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
    subprocess.run(["git", "-C", str(repo), "commit", "-qm", "seed"], check=True)
    return repo


def test_check_no_leak_detects_new_dirty_in_fixer_reachable_path(tmp_path):
    """Reachable dirty paths (cli/, src/, autoresearch/, frontend/) go into
    `actionable` — rollback-eligible because plausibly fixer-caused."""
    repo = _init_repo_with_tracked_dirs(tmp_path)
    snapshot = snapshot_dirty(repo)
    (repo / "cli" / "freddy" / "leaked.py").write_text("leak\n", encoding="utf-8")
    actionable, advisory = check_no_leak(snapshot, main_repo=repo)
    assert actionable == ["cli/freddy/leaked.py"]
    assert advisory == []


def test_check_no_leak_routes_paths_outside_track_scopes_to_advisory(tmp_path):
    """Bug #16: paths outside every track's allowlist (docs/, etc.) go into
    `advisory`, NOT `actionable`. Smoke run 20260422-224908 rolled back 5
    findings because a parallel Claude session was editing docs/plans/* —
    that must not happen."""
    repo = _init_repo_with_tracked_dirs(tmp_path)
    snapshot = snapshot_dirty(repo)
    (repo / "docs" / "plans" / "new-plan.md").write_text("plan\n", encoding="utf-8")
    actionable, advisory = check_no_leak(snapshot, main_repo=repo)
    assert actionable == []
    assert advisory == ["docs/plans/new-plan.md"]


def test_check_no_leak_routes_tests_path_to_advisory(tmp_path):
    """tests/ is outside every track's scope — concurrent test edits don't
    trigger rollback, but they ARE surfaced in advisory for visibility."""
    repo = _init_repo_with_tracked_dirs(tmp_path)
    (repo / "tests").mkdir(parents=True)
    (repo / "tests" / "keep.py").write_text("keep\n", encoding="utf-8")
    subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
    subprocess.run(["git", "-C", str(repo), "commit", "-qm", "seed tests"], check=True)
    snapshot = snapshot_dirty(repo)
    (repo / "tests" / "leaked.py").write_text("leak\n", encoding="utf-8")
    actionable, advisory = check_no_leak(snapshot, main_repo=repo)
    assert actionable == []
    assert advisory == ["tests/leaked.py"]


def test_check_no_leak_still_ignores_harness_artifacts(tmp_path):
    """HARNESS_ARTIFACTS paths (backend.log, sessions/, harness/blocked-*.md)
    are generated by the harness itself and must not count as leaks in either
    category."""
    repo = _init_repo_with_tracked_dirs(tmp_path)
    snapshot = snapshot_dirty(repo)
    (repo / "backend.log").write_text("log\n", encoding="utf-8")
    (repo / "sessions").mkdir(parents=True)
    (repo / "sessions" / "x.json").write_text("{}\n", encoding="utf-8")
    actionable, advisory = check_no_leak(snapshot, main_repo=repo)
    assert actionable == []
    assert advisory == []


def test_check_no_leak_ignores_preexisting_dirty(tmp_path):
    repo = _init_repo(tmp_path)
    (repo / "already.txt").write_text("a\n", encoding="utf-8")
    snapshot = snapshot_dirty(repo)
    assert "already.txt" in snapshot
    actionable, advisory = check_no_leak(snapshot, main_repo=repo)
    assert actionable == []
    assert advisory == []


def test_scope_allowlist_has_three_tracks():
    assert set(SCOPE_ALLOWLIST) == {"a", "b", "c"}
