"""FORMAT step: Deterministic Markdown report generation.

Renders findings, analysis, and generated improvements into a severity-grouped
Markdown report with YAML frontmatter.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import TYPE_CHECKING

from .models import (
    AnalyzeResult,
    AuditFindings,
    FormatResult,
    GenerateResult,
    PageContent,
    Severity,
)

if TYPE_CHECKING:
    from uuid import UUID


SEVERITY_ICONS = {
    Severity.CRITICAL: "\U0001f534",
    Severity.IMPORTANT: "\U0001f7e0",
    Severity.RECOMMENDED: "\U0001f7e1",
    Severity.OPTIONAL: "\U0001f7e2",
}

SEVERITY_LABELS = {
    Severity.CRITICAL: "Critical Issues",
    Severity.IMPORTANT: "Important Improvements",
    Severity.RECOMMENDED: "Recommended Improvements",
    Severity.OPTIONAL: "Optional Enhancements",
}


def format_audit_report(
    audit_id: "UUID",
    page_content: PageContent,
    findings: AuditFindings,
    analyze_result: AnalyzeResult | None,
    generate_result: GenerateResult | None,
    status: str = "complete",
) -> FormatResult:
    """Format complete audit data into Markdown report."""
    lines: list[str] = []

    severity_counts = _count_severities(findings)
    lines.extend(
        _build_frontmatter(
            audit_id=audit_id,
            page_url=page_content.url,
            status=status,
            severity_counts=severity_counts,
        )
    )

    lines.append("# GEO Audit Report")
    lines.append("")
    lines.append(f"**URL:** {page_content.final_url}")
    lines.append(f"**Title:** {_escape_md(page_content.title or 'Untitled')}")
    lines.append(
        f"**Analyzed:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
    )
    lines.append(f"**Word Count:** {page_content.word_count:,}")
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.extend(_build_summary_section(findings, severity_counts))

    if analyze_result and analyze_result.pattern_gaps:
        lines.extend(_build_comparison_section(analyze_result, page_content))

    if analyze_result and analyze_result.content_gaps:
        lines.extend(_build_content_gaps_section(analyze_result))

    grouped_findings = _group_findings_by_severity(findings)

    for severity in [
        Severity.CRITICAL, Severity.IMPORTANT, Severity.RECOMMENDED, Severity.OPTIONAL,
    ]:
        section_findings = grouped_findings.get(severity, [])
        if section_findings or (
            generate_result
            and _has_generated_content_for_severity(severity, generate_result)
        ):
            lines.extend(
                _build_severity_section(
                    severity=severity,
                    section_findings=section_findings,
                    generate_result=generate_result,
                    analyze_result=analyze_result,
                )
            )

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by Freddy GEO Audit Pipeline*")

    report_md = "\n".join(lines)

    return FormatResult(
        report_md=report_md,
        severity_counts=severity_counts,
        word_count=len(report_md.split()),
    )


def _build_frontmatter(
    audit_id: "UUID",
    page_url: str,
    status: str,
    severity_counts: dict[str, int],
) -> list[str]:
    return [
        "---",
        "type: geo-audit",
        f"audit_id: {audit_id}",
        f"page_url: {page_url}",
        f"status: {status}",
        f"generated_at: {datetime.now(timezone.utc).isoformat()}",
        "severity_counts:",
        f"  critical: {severity_counts.get('critical', 0)}",
        f"  important: {severity_counts.get('important', 0)}",
        f"  recommended: {severity_counts.get('recommended', 0)}",
        f"  optional: {severity_counts.get('optional', 0)}",
        "---",
        "",
    ]


def _build_summary_section(
    findings: AuditFindings, severity_counts: dict[str, int],
) -> list[str]:
    lines = [
        "## Summary",
        "",
        f"Analyzed **{findings.factors_checked}** GEO factors. "
        f"Found **{findings.factors_missing}** areas for improvement.",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]

    for severity in [
        Severity.CRITICAL, Severity.IMPORTANT, Severity.RECOMMENDED, Severity.OPTIONAL,
    ]:
        icon = SEVERITY_ICONS[severity]
        count = severity_counts.get(severity.value, 0)
        lines.append(f"| {icon} {severity.value.title()} | {count} |")

    lines.extend(["", "---", ""])
    return lines


def _build_comparison_section(
    analyze_result: AnalyzeResult, page_content: PageContent,
) -> list[str]:
    gaps = analyze_result.pattern_gaps
    if gaps is None:
        return []

    rows: list[str] = []

    if gaps.faq_section_pct is not None:
        has_faq = "FAQPage" in (page_content.schema_types or [])
        rows.append(
            f"| FAQ Schema | {gaps.faq_section_pct:.0f}% have | "
            f"{'Present' if has_faq else 'Missing'} | "
            f"{'None' if has_faq else 'Add FAQ schema'} |"
        )

    if gaps.comparison_table_pct is not None:
        rows.append(
            f"| Comparison Tables | {gaps.comparison_table_pct:.0f}% have | "
            "Unknown | Consider adding |"
        )

    if gaps.cited_median_age_days is not None:
        rows.append(
            f"| Content Freshness | Avg {gaps.cited_median_age_days:.0f} days old | "
            "Unknown | Update regularly |"
        )

    if not rows:
        return []

    return [
        "## Your Page vs. Cited Pages",
        "",
        "Based on analysis of pages that AI platforms cite for similar topics:",
        "",
        "| Element | Cited Pages | Your Page | Gap |",
        "|---------|-------------|-----------|-----|",
        *rows,
        "",
        "---",
        "",
    ]


def _build_content_gaps_section(analyze_result: AnalyzeResult) -> list[str]:
    gaps = analyze_result.content_gaps
    if not gaps:
        return []

    critical = [g for g in gaps if g.importance == "critical"]
    important = [g for g in gaps if g.importance == "important"]
    recommended = [g for g in gaps if g.importance == "recommended"]

    lines = [
        "## Content Gap Analysis",
        "",
        "Topics that AI-cited pages cover but your page does not:",
        "",
        "| Topic | Cited Coverage | Priority | Source |",
        "|-------|---------------|----------|--------|",
    ]

    for gap in gaps:
        icon = {"critical": "\U0001f534", "important": "\U0001f7e0", "recommended": "\U0001f7e1"}.get(
            gap.importance, "\U0001f7e1"
        )
        source_label = f" [{gap.source}]" if gap.source else ""
        lines.append(
            f"| {_escape_md(gap.topic_name)} | {gap.coverage_pct:.0f}% |"
            f" {icon} {gap.importance.title()} |{source_label} |"
        )

    lines.append("")

    if critical:
        lines.append(
            f"**\U0001f534 {len(critical)} critical gap{'s' if len(critical) != 1 else ''}** "
            "— topics covered by 75%+ of cited pages. Address these first."
        )
    if important:
        lines.append(
            f"**\U0001f7e0 {len(important)} important gap{'s' if len(important) != 1 else ''}** "
            "— topics covered by 60-74% of cited pages."
        )
    if recommended:
        lines.append(
            f"**\U0001f7e1 {len(recommended)} recommended gap{'s' if len(recommended) != 1 else ''}** "
            "— topics covered by 50-59% of cited pages."
        )

    lines.extend(["", "---", ""])
    return lines


def _build_severity_section(
    severity: Severity,
    section_findings: list,
    generate_result: GenerateResult | None,
    analyze_result: AnalyzeResult | None,
) -> list[str]:
    icon = SEVERITY_ICONS[severity]
    label = SEVERITY_LABELS[severity]
    lines = [f"## {icon} {label}", ""]

    for finding in sorted(section_findings, key=lambda f: f.factor_id):
        if finding.detected is False:
            lines.append(f"### Missing: {finding.factor_name}")
            lines.append("")
            if finding.details:
                lines.append(finding.details)
                lines.append("")
            if finding.evidence:
                lines.append("**Evidence:**")
                for ev in finding.evidence[:3]:
                    lines.append(f"- {_escape_md(ev)}")
                lines.append("")

    if generate_result:
        lines.extend(
            _render_generated_content(severity, generate_result, analyze_result)
        )

    lines.append("")
    return lines


def _render_generated_content(
    severity: Severity,
    generate_result: GenerateResult,
    analyze_result: AnalyzeResult | None,
) -> list[str]:
    lines: list[str] = []

    if severity == Severity.CRITICAL:
        if analyze_result and analyze_result.content_gaps:
            critical_gaps = [g for g in analyze_result.content_gaps if g.coverage_pct >= 80]
            for gap in critical_gaps:
                fill_in = next(
                    (f for f in generate_result.content_fillins if f.topic_name == gap.topic_name),
                    None,
                )
                if fill_in:
                    lines.extend(_render_content_fill_in(fill_in))

    if severity == Severity.IMPORTANT:
        if generate_result.improved_intro:
            lines.append("### Rewrite Introduction (Answer-First)")
            lines.append("")
            lines.append("Your intro should answer the query directly. 82% of cited pages do this.")
            lines.append("")
            lines.append("**Suggested rewrite:**")
            lines.append("")
            lines.append("```")
            lines.append(generate_result.improved_intro.text)
            lines.append("```")
            lines.append("")

    if severity == Severity.RECOMMENDED:
        if generate_result.faq_generation and generate_result.faq_generation.items:
            lines.append("### Add FAQ Section")
            lines.append("")
            lines.append("78% of cited pages in your topic have FAQ sections. Add these questions:")
            lines.append("")
            for item in generate_result.faq_generation.items:
                lines.append(f"**Q: {item.question}**")
                lines.append("")
                lines.append(f"A: {item.answer}")
                lines.append("")

            from .generator import build_faq_schema

            faq_schema = build_faq_schema(generate_result.faq_generation.items)
            if faq_schema:
                lines.append("**FAQPage Schema:**")
                lines.append("")
                lines.append("```json")
                lines.append(faq_schema)
                lines.append("```")
                lines.append("")

    if severity == Severity.OPTIONAL:
        if generate_result.structural_suggestions:
            lines.append("### Structural Improvements")
            lines.append("")
            for suggestion in generate_result.structural_suggestions:
                lines.append(
                    f"- **{suggestion.suggestion_type}**: {suggestion.description}"
                )
            lines.append("")

    return lines


def _render_content_fill_in(fill_in) -> list[str]:
    lines = [
        f"### Content Gap: {fill_in.topic_name}",
        "",
        f"**{fill_in.coverage_pct:.0f}% of cited pages** discuss this topic. Your page doesn't.",
        "",
        "**Generated content:**",
        "",
        "> " + fill_in.generated_paragraphs.replace("\n", "\n> "),
        "",
    ]
    if fill_in.placement_after:
        lines.append(f"**Placement:** {fill_in.placement_after}")
        lines.append("")
    return lines


def _count_severities(findings: AuditFindings) -> dict[str, int]:
    counts = {"critical": 0, "important": 0, "recommended": 0, "optional": 0}
    for finding in findings.findings:
        if finding.detected is False:
            counts[finding.severity.value] = counts.get(finding.severity.value, 0) + 1
    return counts


def _group_findings_by_severity(findings: AuditFindings) -> dict[Severity, list]:
    grouped: dict[Severity, list] = {}
    for finding in findings.findings:
        if finding.severity not in grouped:
            grouped[finding.severity] = []
        grouped[finding.severity].append(finding)
    return grouped


def _has_generated_content_for_severity(
    severity: Severity, generate_result: GenerateResult
) -> bool:
    if severity == Severity.IMPORTANT:
        return generate_result.improved_intro is not None
    if severity == Severity.RECOMMENDED:
        return (
            generate_result.faq_generation is not None
            and len(generate_result.faq_generation.items) > 0
        )
    if severity == Severity.OPTIONAL:
        return len(generate_result.structural_suggestions) > 0
    return False


def _escape_md(text: str) -> str:
    text = text.replace("\\", "\\\\")
    text = re.sub(r"(javascript|data|vbscript):", r"\1\\:", text, flags=re.IGNORECASE)
    for char in ["*", "_", "`", "[", "]", "(", ")", "#", "+", "-", ".", "!", "|", "<", ">"]:
        text = text.replace(char, f"\\{char}")
    return text


def _escape_yaml(text: str) -> str:
    if any(c in text for c in [":", '"', "'", "\n", "\r", "\t", "\\", "#"]):
        escaped = (
            text.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
        )
        return f'"{escaped}"'
    return text
